import { Component, OnInit } from '@angular/core';
import { Subscription, interval } from 'rxjs';

@Component({
  selector: 'app-english-turkish',
  templateUrl: './english-turkish.component.html',
  styleUrls: ['./english-turkish.component.css']
})
export class EnglishTurkishComponent implements OnInit {


  verbDictionary = new Map();
  verbDictionary2 = new Map();
  
  randomKey:any;
  randomKey2:any;
  turkishEquivalent:any;
  turkishEquivalent2:any;
  autorandomKey:any="English";
  autoturkishEquivalent:any="Türkçe";
  selectedWaitTime: number = 5;
  private intervalSubscription: Subscription | undefined;
  userInput: string = ''; // Kullanıcının girdiği Türkçe kelime
  userInput2: string = ''; // Kullanıcının girdiği İngilizce kelime
  isTranslationCorrect: boolean = false; // Türkçe kelimenin doğruluğu
  isTranslationCorrect2: boolean = false; // İngilizce kelimenin doğruluğu
 
 
 
 
   constructor() {
    
     
   }
 
   ngOnInit(): void {
     
     this.load();
     this.load2();
     this.get();
     this.get2();
 
     this.startInterval();
     
     
   }
 
 
   checkTranslation() {
     // Kullanıcının girdiği kelimeyi kontrol et
     this.isTranslationCorrect = this.userInput.toLowerCase() === this.turkishEquivalent.toLowerCase();
   }
   checkTranslation2() {
    // Kullanıcının girdiği kelimeyi kontrol et
    this.isTranslationCorrect2 = this.userInput2.toLowerCase() === this.randomKey2.toLowerCase();
  }
 
   ngOnDestroy() {
     this.stopInterval();
   }
 
   onChangeWaitTime(event: any) {
     this.selectedWaitTime = +event.target.value;
     this.restartInterval();
     
   }
 
 
    startInterval() {
     this.intervalSubscription = interval(this.selectedWaitTime * 1000).subscribe(() => {
       this.autoget();
       
     });
   }
 
   private stopInterval() {
     if (this.intervalSubscription) {
       this.intervalSubscription.unsubscribe();
     }
   }
 
   private restartInterval() {
     this.stopInterval();
     this.startInterval();
   }
 
   del(){
 
     this.verbDictionary.delete(this.randomKey);
     console.log("Silindi:", this.randomKey);
     this.get();
     
 
   }
 
   showWord(){
     this.userInput=this.turkishEquivalent;
     this.isTranslationCorrect=true;
 
   }
   hint(){
    this.userInput=this.turkishEquivalent.substring(0,2);
    
  }
 
   autoget=()=>{
 // Rastgele bir kelime seçme
 let keys = Array.from(this.verbDictionary.keys());
  this.autorandomKey = keys[Math.floor(Math.random() * keys.length)];
 
 // Seçilen kelimenin Türkçe karşılığını alma
 this.autoturkishEquivalent = this.verbDictionary.get(this.autorandomKey);
 
     
   }
 
   get(){
 
     this.userInput="";
     this.isTranslationCorrect=false;
     // Rastgele bir kelime seçme
 let keys = Array.from(this.verbDictionary.keys());
  this.randomKey = keys[Math.floor(Math.random() * keys.length)];
 
 // Seçilen kelimenin Türkçe karşılığını alma
 this.turkishEquivalent = this.verbDictionary.get(this.randomKey);
 
 // Sonucu ekrana basma
 console.log("İngilizce:", this.randomKey);
 console.log("Türkçe:", this.turkishEquivalent);
   }
 
   load(){
    
     this.verbDictionary.set("the", "o");
 this.verbDictionary.set("and", "ve");
 this.verbDictionary.set("of", "nin");
 this.verbDictionary.set("to", "e");
 this.verbDictionary.set("a", "bir");
 this.verbDictionary.set("I", "Ben");
 this.verbDictionary.set("in", "içinde");
 this.verbDictionary.set("you", "sen");
 this.verbDictionary.set("that", "o");
 this.verbDictionary.set("it", "o");
 this.verbDictionary.set("for", "için");
 this.verbDictionary.set("he", "o");
 this.verbDictionary.set("on", "üzerinde");
 this.verbDictionary.set("we", "biz");
 this.verbDictionary.set("they", "onlar");
 this.verbDictionary.set("be", "olmak");
 this.verbDictionary.set("with", "ile");
 this.verbDictionary.set("this", "bu");
 this.verbDictionary.set("have", "sahip olmak");
 this.verbDictionary.set("but", "ama");
 this.verbDictionary.set("as", "olarak");
 this.verbDictionary.set("not", "değil");
 this.verbDictionary.set("at", "de");
 this.verbDictionary.set("what", "ne");
 this.verbDictionary.set("so", "bu yüzden");
 this.verbDictionary.set("there", "orada");
 this.verbDictionary.set("or", "veya");
 this.verbDictionary.set("one", "bir");
 this.verbDictionary.set("by", "tarafından");
 this.verbDictionary.set("from", "den");
 this.verbDictionary.set("all", "tüm");
 this.verbDictionary.set("she", "o");
 this.verbDictionary.set("no", "hayır");
 this.verbDictionary.set("his", "onun");
 this.verbDictionary.set("do", "yapmak");
 this.verbDictionary.set("can", "yapabilir");
 this.verbDictionary.set("if", "eğer");
 this.verbDictionary.set("about", "hakkında");
 this.verbDictionary.set("my", "benim");
 this.verbDictionary.set("her", "onun");
 this.verbDictionary.set("know", "bilmek");
 this.verbDictionary.set("like", "gibi");
 this.verbDictionary.set("well", "iyi");
 this.verbDictionary.set("just", "sadece");
 this.verbDictionary.set("think", "düşünmek");
 this.verbDictionary.set("right", "doğru");
 this.verbDictionary.set("then", "sonra");
 this.verbDictionary.set("now", "şimdi");
 this.verbDictionary.set("get", "almak");
 this.verbDictionary.set("time", "zaman");
 this.verbDictionary.set("again", "tekrar");
 this.verbDictionary.set("own", "kendi");
 this.verbDictionary.set("quite", "oldukça");
 this.verbDictionary.set("give", "vermek");
 this.verbDictionary.set("home", "ev");
 this.verbDictionary.set("tell", "söylemek");
 this.verbDictionary.set("world", "dünya");
 this.verbDictionary.set("use", "kullanmak");
 this.verbDictionary.set("always", "her zaman");
 this.verbDictionary.set("great", "harika");
 this.verbDictionary.set("problem", "sorun");
 this.verbDictionary.set("love", "sevgi");
 this.verbDictionary.set("name", "isim");
 this.verbDictionary.set("percent", "yüzde");
 this.verbDictionary.set("call", "aramak");
 this.verbDictionary.set("water", "su");
 this.verbDictionary.set("important", "önemli");
 this.verbDictionary.set("country", "ülke");
 this.verbDictionary.set("small", "küçük");
 this.verbDictionary.set("feel", "hiss etmek");
 this.verbDictionary.set("company", "şirket");
 this.verbDictionary.set("perhaps", "belki");
 this.verbDictionary.set("ago", "önce");
 this.verbDictionary.set("hard", "zor");
 this.verbDictionary.set("form", "form");
 this.verbDictionary.set("party", "parti");
 this.verbDictionary.set("means", "anlamına gelir");
 this.verbDictionary.set("often", "sık sık");
 this.verbDictionary.set("example", "örnek");
 this.verbDictionary.set("play", "oynamak");
 this.verbDictionary.set("fine", "iyi");
 this.verbDictionary.set("certain", "kesin");
 this.verbDictionary.set("turn", "dönmek");
 this.verbDictionary.set("control", "kontrol etmek");
 this.verbDictionary.set("sometimes", "bazen");
 this.verbDictionary.set("political", "siyasi");
 this.verbDictionary.set("top", "üst");
 this.verbDictionary.set("story", "hikaye");
 this.verbDictionary.set("door", "kapı");
 this.verbDictionary.set("hear", "duymak");
 this.verbDictionary.set("thinking", "düşünce");
 this.verbDictionary.set("stay", "kalmak");
 this.verbDictionary.set("market", "pazar");
 this.verbDictionary.set("age", "yaş");
 this.verbDictionary.set("support", "destek");
 this.verbDictionary.set("clear", "net");
 this.verbDictionary.set("police", "polis");
 this.verbDictionary.set("department", "departman");
 this.verbDictionary.set("table", "masa");
 this.verbDictionary.set("experience", "deneyim");
 
 this.verbDictionary.set("situation", "durum");
 this.verbDictionary.set("alright", "tamam");
 this.verbDictionary.set("court", "mahkeme");
 this.verbDictionary.set("exactly", "tam olarak");
 this.verbDictionary.set("main", "ana");
 this.verbDictionary.set("rest", "geri kalan");
 this.verbDictionary.set("son", "oğul");
 this.verbDictionary.set("miss", "kaçırmak");
 this.verbDictionary.set("hold", "tutmak");
 this.verbDictionary.set("especially", "özellikle");
 this.verbDictionary.set("thanks", "teşekkürler");
 this.verbDictionary.set("middle", "orta");
 this.verbDictionary.set("suppose", "varsaymak");
 this.verbDictionary.set("field", "alan");
 this.verbDictionary.set("game", "oyun");
 this.verbDictionary.set("test", "test");
 this.verbDictionary.set("dad", "baba");
 this.verbDictionary.set("section", "bölüm");
 this.verbDictionary.set("industry", "endüstri");
 this.verbDictionary.set("sir", "efendi");
 this.verbDictionary.set("finally", "sonunda");
 this.verbDictionary.set("quality", "kalite");
 this.verbDictionary.set("happen", "olmak");
 this.verbDictionary.set("amount", "miktar");
 this.verbDictionary.set("role", "rol");
 this.verbDictionary.set("force", "kuvvet");
 this.verbDictionary.set("difference", "fark");
 this.verbDictionary.set("phone", "telefon");
 this.verbDictionary.set("forward", "ileri");
 this.verbDictionary.set("member", "üye");
 this.verbDictionary.set("president", "başkan");
 this.verbDictionary.set("production", "üretim");
 this.verbDictionary.set("trouble", "sorun");
 this.verbDictionary.set("management", "yönetim");
 this.verbDictionary.set("account", "hesap");
 this.verbDictionary.set("size", "boyut");
 this.verbDictionary.set("hot", "sıcak");
 this.verbDictionary.set("worth", "değer");
 this.verbDictionary.set("simple", "basit");
 this.verbDictionary.set("hell", "cehennem");
 this.verbDictionary.set("approach", "yaklaşım");
 this.verbDictionary.set("computer", "bilgisayar");
 this.verbDictionary.set("straight", "düz");
 this.verbDictionary.set("space", "uzay");
 this.verbDictionary.set("colour", "renk");
 this.verbDictionary.set("fall", "sonbahar");
 this.verbDictionary.set("performance", "performans");
 this.verbDictionary.set("culture", "kültür");
 this.verbDictionary.set("pick", "seçmek");
 this.verbDictionary.set("river", "nehir");
 this.verbDictionary.set("kill", "öldürmek");
 this.verbDictionary.set("follow", "takip etmek");
 this.verbDictionary.set("function", "fonksiyon");
 this.verbDictionary.set("practice", "pratik");
 this.verbDictionary.set("former", "eski");
 this.verbDictionary.set("sister", "kız kardeş");
 this.verbDictionary.set("absolutely", "kesinlikle");
 this.verbDictionary.set("somewhere", "bir yerlerde");
 this.verbDictionary.set("include", "içermek");
 this.verbDictionary.set("Sunday", "Pazar");
 this.verbDictionary.set("television", "televizyon");
 this.verbDictionary.set("western", "batı");
 this.verbDictionary.set("opportunity", "fırsat");
 this.verbDictionary.set("key", "anahtar");
 this.verbDictionary.set("series", "dizi");
 this.verbDictionary.set("born", "doğmak");
 this.verbDictionary.set("park", "park");
 this.verbDictionary.set("response", "tepki");
 this.verbDictionary.set("style", "stil");
 this.verbDictionary.set("hall", "salon");
 this.verbDictionary.set("which", "hangi");
 this.verbDictionary.set("up", "yukarı");
 this.verbDictionary.set("out", "dışarı");
 this.verbDictionary.set("would", "olurdu");
 this.verbDictionary.set("when", "ne zaman");
 this.verbDictionary.set("your", "senin");
 this.verbDictionary.set("will", "olacak");
 this.verbDictionary.set("their", "onların");
 this.verbDictionary.set("who", "kim");
 this.verbDictionary.set("some", "bazı");
 this.verbDictionary.set("two", "iki");
 this.verbDictionary.set("because", "çünkü");
 this.verbDictionary.set("how", "nasıl");
 this.verbDictionary.set("other", "diğer");
 this.verbDictionary.set("could", "olabilir");
 this.verbDictionary.set("our", "bizim");
 this.verbDictionary.set("into", "içine");
 this.verbDictionary.set("these", "bunlar");
 this.verbDictionary.set("than", "daha");
 this.verbDictionary.set("any", "herhangi");
 this.verbDictionary.set("where", "nerede");
 this.verbDictionary.set("over", "üzerinde");
 this.verbDictionary.set("back", "geri");
 this.verbDictionary.set("first", "ilk");
 this.verbDictionary.set("much", "çok");
 this.verbDictionary.set("down", "aşağı");
 this.verbDictionary.set("its", "onun");
 this.verbDictionary.set("should", "malı");
 this.verbDictionary.set("after", "sonra");
 this.verbDictionary.set("those", "onlar");
 
 
 this.verbDictionary.set("may", "olabilir");
 this.verbDictionary.set("something", "bir şey");
 this.verbDictionary.set("three", "üç");
 this.verbDictionary.set("little", "az");
 this.verbDictionary.set("many", "birçok");
 this.verbDictionary.set("why", "neden");
 this.verbDictionary.set("before", "önce");
 this.verbDictionary.set("such", "böyle");
 this.verbDictionary.set("off", "kapalı");
 this.verbDictionary.set("through", "aracılığıyla");
 this.verbDictionary.set("go", "gitmek");
 this.verbDictionary.set("yes", "evet");
 this.verbDictionary.set("very", "çok");
 this.verbDictionary.set("see", "görmek");
 this.verbDictionary.set("people", "insanlar");
 this.verbDictionary.set("here", "burada");
 this.verbDictionary.set("good", "iyi");
 this.verbDictionary.set("only", "sadece");
 this.verbDictionary.set("really", "gerçekten");
 this.verbDictionary.set("say", "demek");
 this.verbDictionary.set("kind", "tür");
 this.verbDictionary.set("actually", "aslında");
 this.verbDictionary.set("sort", "sıralama");
 this.verbDictionary.set("government", "hükümet");
 this.verbDictionary.set("house", "ev");
 this.verbDictionary.set("find", "bulmak");
 this.verbDictionary.set("place", "yer");
 this.verbDictionary.set("different", "farklı");
 this.verbDictionary.set("part", "bölüm");
 this.verbDictionary.set("sure", "emin");
 this.verbDictionary.set("real", "gerçek");
 this.verbDictionary.set("best", "en iyi");
 this.verbDictionary.set("laugh", "gülmek");
 this.verbDictionary.set("room", "oda");
 this.verbDictionary.set("remember", "hatırlamak");
 this.verbDictionary.set("nice", "hoş");
 this.verbDictionary.set("rather", "tercihen");
 this.verbDictionary.set("public", "genel");
 this.verbDictionary.set("mother", "anne");
 this.verbDictionary.set("less", "daha az");
 this.verbDictionary.set("care", "önem vermek");
 this.verbDictionary.set("ask", "sormak");
 this.verbDictionary.set("social", "sosyal");
 this.verbDictionary.set("national", "ulusal");
 this.verbDictionary.set("book", "kitap");
 this.verbDictionary.set("father", "baba");
 this.verbDictionary.set("bad", "kötü");
 this.verbDictionary.set("war", "savaş");
 this.verbDictionary.set("large", "büyük");
 this.verbDictionary.set("food", "yiyecek");
 this.verbDictionary.set("moment", "an");
 this.verbDictionary.set("sense", "anlam");
 this.verbDictionary.set("law", "kanun");
 this.verbDictionary.set("programme", "program");
 this.verbDictionary.set("free", "ücretsiz");
 this.verbDictionary.set("front", "ön");
 this.verbDictionary.set("language", "dil");
 this.verbDictionary.set("study", "çalışma");
 this.verbDictionary.set("white", "beyaz");
 this.verbDictionary.set("late", "geç");
 this.verbDictionary.set("cut", "kesmek");
 this.verbDictionary.set("south", "güney");
 this.verbDictionary.set("report", "rapor");
 this.verbDictionary.set("soon", "yakında");
 this.verbDictionary.set("usually", "genellikle");
 this.verbDictionary.set("bring", "getirmek");
 this.verbDictionary.set("society", "toplum");
 this.verbDictionary.set("history", "tarih");
 this.verbDictionary.set("couple", "çift");
 this.verbDictionary.set("available", "müsait");
 this.verbDictionary.set("mum", "anne");
 this.verbDictionary.set("church", "kilise");
 this.verbDictionary.set("rate", "oran");
 this.verbDictionary.set("council", "konsey");
 this.verbDictionary.set("answer", "cevap");
 this.verbDictionary.set("common", "ortak");
 this.verbDictionary.set("north", "kuzey");
 this.verbDictionary.set("happy", "mutlu");
 this.verbDictionary.set("building", "bina");
 this.verbDictionary.set("instead", "bunun yerine");
 this.verbDictionary.set("action", "hareket");
 this.verbDictionary.set("personal", "kişisel");
 this.verbDictionary.set("write", "yazmak");
 this.verbDictionary.set("team", "takım");
 this.verbDictionary.set("heart", "kalp");
 this.verbDictionary.set("value", "değer");
 this.verbDictionary.set("issue", "sorun");
 this.verbDictionary.set("various", "çeşitli");
 this.verbDictionary.set("alone", "yalnız");
 this.verbDictionary.set("letter", "mektup");
 this.verbDictionary.set("range", "aralık");
 this.verbDictionary.set("ground", "zemin");
 this.verbDictionary.set("reading", "okuma");
 this.verbDictionary.set("tomorrow", "yarın");
 this.verbDictionary.set("due", "nedeniyle");
 this.verbDictionary.set("knowledge", "bilgi");
 this.verbDictionary.set("brother", "erkek kardeş");
 
 this.verbDictionary.set("decision", "karar");
 this.verbDictionary.set("beautiful", "güzel");
 this.verbDictionary.set("standard", "standart");
 this.verbDictionary.set("record", "kayıt");
 this.verbDictionary.set("ball", "top");
 this.verbDictionary.set("piece", "parça");
 this.verbDictionary.set("interested", "ilgili");
 this.verbDictionary.set("natural", "doğal");
 this.verbDictionary.set("agree", "katılmak");
 this.verbDictionary.set("modern", "modern");
 this.verbDictionary.set("student", "öğrenci");
 this.verbDictionary.set("summer", "yaz");
 this.verbDictionary.set("pressure", "baskı");
 this.verbDictionary.set("picture", "resim");
 this.verbDictionary.set("relationship", "ilişki");
 this.verbDictionary.set("dark", "karanlık");
 this.verbDictionary.set("drive", "sürmek");
 this.verbDictionary.set("visit", "ziyaret etmek");
 this.verbDictionary.set("green", "yeşil");
 this.verbDictionary.set("teaching", "öğretim");
 this.verbDictionary.set("hotel", "otel");
 this.verbDictionary.set("truth", "gerçek");
 this.verbDictionary.set("design", "tasarım");
 this.verbDictionary.set("wonder", "merak etmek");
 this.verbDictionary.set("dinner", "akşam yemeği");
 this.verbDictionary.set("medical", "medikal");
 this.verbDictionary.set("fair", "adil");
 this.verbDictionary.set("radio", "radyo");
 this.verbDictionary.set("legal", "hukuki");
 this.verbDictionary.set("pass", "geçmek");
 this.verbDictionary.set("nearly", "neredeyse");
 this.verbDictionary.set("daughter", "kız");
 this.verbDictionary.set("trust", "güven");
 this.verbDictionary.set("window", "pencere");
 this.verbDictionary.set("carry", "taşımak");
 this.verbDictionary.set("rights", "haklar");
 this.verbDictionary.set("fight", "kavga");
 this.verbDictionary.set("environment", "çevre");
 this.verbDictionary.set("cool", "serin");
 this.verbDictionary.set("sex", "cinsiyet");
 this.verbDictionary.set("eye", "göz");
 this.verbDictionary.set("region", "bölge");
 this.verbDictionary.set("still", "hala");
 this.verbDictionary.set("last", "son");
 this.verbDictionary.set("being", "varlık");
 this.verbDictionary.set("must", "meli");
 this.verbDictionary.set("another", "başka");
 this.verbDictionary.set("between", "arasında");
 this.verbDictionary.set("might", "belki");
 this.verbDictionary.set("both", "her ikisi de");
 this.verbDictionary.set("five", "beş");
 this.verbDictionary.set("four", "dört");
 this.verbDictionary.set("around", "etrafında");
 
 this.verbDictionary.set("while", "iken");
 this.verbDictionary.set("each", "her biri");
 this.verbDictionary.set("under", "altında");
 this.verbDictionary.set("away", "uzakta");
 this.verbDictionary.set("every", "her");
 this.verbDictionary.set("next", "sonraki");
 this.verbDictionary.set("anything", "herhangi bir şey");
 this.verbDictionary.set("few", "birkaç");
 this.verbDictionary.set("though", "rağmen");
 this.verbDictionary.set("since", "beri");
 this.verbDictionary.set("against", "karşı");
 this.verbDictionary.set("second", "ikinci");
 this.verbDictionary.set("nothing", "hiçbir şey");
 this.verbDictionary.set("without", "olmadan");
 this.verbDictionary.set("during", "sırasında");
 this.verbDictionary.set("six", "altı");
 this.verbDictionary.set("enough", "yeterli");
 this.verbDictionary.set("once", "bir kere");
 this.verbDictionary.set("however", "ancak");
 this.verbDictionary.set("half", "yarım");
 this.verbDictionary.set("yet", "henüz");
 this.verbDictionary.set("whether", "olup olmadığı");
 this.verbDictionary.set("everything", "her şey");
 this.verbDictionary.set("until", "kadar");
 this.verbDictionary.set("hundred", "yüz");
 this.verbDictionary.set("within", "içinde");
 this.verbDictionary.set("ten", "on");
 this.verbDictionary.set("twenty", "yirmi");
 this.verbDictionary.set("either", "ya");
 this.verbDictionary.set("mean", "anlamına gelmek");
 this.verbDictionary.set("come", "gelmek");
 this.verbDictionary.set("also", "ayrıca");
 this.verbDictionary.set("okay", "tamam");
 this.verbDictionary.set("want", "istemek");
 this.verbDictionary.set("way", "yol");
 this.verbDictionary.set("even", "bile");
 this.verbDictionary.set("new", "yeni");
 this.verbDictionary.set("too", "çok");
 this.verbDictionary.set("work", "çalışmak");
 this.verbDictionary.set("point", "nokta");
 this.verbDictionary.set("number", "sayı");
 this.verbDictionary.set("school", "okul");
 this.verbDictionary.set("end", "son");
 this.verbDictionary.set("money", "para");
 this.verbDictionary.set("better", "daha iyi");
 this.verbDictionary.set("big", "büyük");
 this.verbDictionary.set("probably", "muhtemelen");
 this.verbDictionary.set("fact", "gerçek");
 this.verbDictionary.set("bit", "biraz");
 this.verbDictionary.set("later", "sonra");
 
 
 this.verbDictionary.set("hand", "el");
 this.verbDictionary.set("already", "zaten");
 this.verbDictionary.set("mind", "akıl");
 this.verbDictionary.set("thank", "teşekkür etmek");
 this.verbDictionary.set("job", "iş");
 this.verbDictionary.set("business", "iş");
 this.verbDictionary.set("else", "başka");
 this.verbDictionary.set("group", "grup");
 this.verbDictionary.set("question", "soru");
 this.verbDictionary.set("open", "açık");
 this.verbDictionary.set("pretty", "güzel");
 this.verbDictionary.set("matter", "önemli");
 this.verbDictionary.set("information", "bilgi");
 this.verbDictionary.set("hey", "hey");
 this.verbDictionary.set("face", "yüz");
 this.verbDictionary.set("early", "erken");
 this.verbDictionary.set("please", "lütfen");
 this.verbDictionary.set("pay", "ödemek");
 this.verbDictionary.set("woman", "kadın");
 this.verbDictionary.set("wrong", "yanlış");
 this.verbDictionary.set("further", "daha fazla");
 this.verbDictionary.set("move", "hareket etmek");
 this.verbDictionary.set("guy", "adam");
 this.verbDictionary.set("girl", "kız");
 this.verbDictionary.set("wife", "eş");
 this.verbDictionary.set("education", "eğitim");
 this.verbDictionary.set("close", "kapat");
 this.verbDictionary.set("stop", "durmak");
 this.verbDictionary.set("class", "sınıf");
 this.verbDictionary.set("short", "kısa");
 this.verbDictionary.set("community", "topluluk");
 this.verbDictionary.set("cost", "maliyet");
 this.verbDictionary.set("friend", "arkadaş");
 this.verbDictionary.set("economic", "ekonomik");
 this.verbDictionary.set("position", "pozisyon");
 this.verbDictionary.set("period", "dönem");
 this.verbDictionary.set("policy", "politika");
 this.verbDictionary.set("special", "özel");
 this.verbDictionary.set("centre", "merkez");
 this.verbDictionary.set("low", "düşük");
 this.verbDictionary.set("meet", "tanışmak");
 this.verbDictionary.set("west", "batı");
 this.verbDictionary.set("art", "sanat");
 this.verbDictionary.set("century", "yüzyıl");
 this.verbDictionary.set("dead", "ölü");
 this.verbDictionary.set("particularly", "özellikle");
 this.verbDictionary.set("hi", "merhaba");
 this.verbDictionary.set("result", "sonuç");
 this.verbDictionary.set("plan", "plan");
 this.verbDictionary.set("ready", "hazır");
 
 this.verbDictionary.set("sound", "ses");
 this.verbDictionary.set("international", "uluslararası");
 this.verbDictionary.set("necessary", "gerekli");
 this.verbDictionary.set("training", "eğitim");
 this.verbDictionary.set("ok", "tamam");
 this.verbDictionary.set("according", "göre");
 this.verbDictionary.set("single", "tek");
 this.verbDictionary.set("term", "terim");
 this.verbDictionary.set("stand", "durmak");
 this.verbDictionary.set("hair", "saç");
 this.verbDictionary.set("bank", "banka");
 this.verbDictionary.set("obviously", "açıkça");
 this.verbDictionary.set("east", "doğu");
 this.verbDictionary.set("writing", "yazma");
 this.verbDictionary.set("return", "geri dönme");
 this.verbDictionary.set("break", "mola");
 this.verbDictionary.set("project", "proje");
 this.verbDictionary.set("minute", "dakika");
 this.verbDictionary.set("check", "kontrol etmek");
 this.verbDictionary.set("wish", "dilemek");
 this.verbDictionary.set("serious", "ciddi");
 this.verbDictionary.set("minister", "bakan");
 this.verbDictionary.set("growth", "büyüme");
 this.verbDictionary.set("blood", "kan");
 this.verbDictionary.set("bill", "fatura");
 this.verbDictionary.set("trade", "ticaret");
 this.verbDictionary.set("list", "liste");
 this.verbDictionary.set("basis", "temel");
 this.verbDictionary.set("floor", "zemin");
 this.verbDictionary.set("island", "ada");
 this.verbDictionary.set("sign", "işaret");
 this.verbDictionary.set("basic", "temel");
 this.verbDictionary.set("military", "askeri");
 this.verbDictionary.set("press", "basın");
 this.verbDictionary.set("spend", "harcamak");
 this.verbDictionary.set("consider", "düşünmek");
 this.verbDictionary.set("sea", "deniz");
 this.verbDictionary.set("complete", "tamamlamak");
 this.verbDictionary.set("bye", "hoşça kal");
 this.verbDictionary.set("theory", "teori");
 this.verbDictionary.set("shot", "ateş");
 this.verbDictionary.set("energy", "enerji");
 this.verbDictionary.set("offer", "teklif");
 this.verbDictionary.set("patients", "hastalar");
 this.verbDictionary.set("significant", "önemli");
 this.verbDictionary.set("deep", "derin");
 this.verbDictionary.set("begin", "başlamak");
 this.verbDictionary.set("quickly", "hızlıca");
 this.verbDictionary.set("charge", "ücret");
 this.verbDictionary.set("original", "orijinal");
 
 this.verbDictionary.set("dollar", "dolar");
 this.verbDictionary.set("square", "kare");
 this.verbDictionary.set("direct", "doğrudan");
 this.verbDictionary.set("forty", "kırk");
 this.verbDictionary.set("nobody", "hiç kimse");
 this.verbDictionary.set("unless", "eğer ki");
 this.verbDictionary.set("mine", "benimki");
 this.verbDictionary.set("anybody", "herhangi biri");
 this.verbDictionary.set("till", "kadar");
 this.verbDictionary.set("herself", "kendi");
 this.verbDictionary.set("twelve", "on iki");
 this.verbDictionary.set("fifteen", "on beş");
 this.verbDictionary.set("beyond", "ötesinde");
 this.verbDictionary.set("whom", "kimi");
 this.verbDictionary.set("below", "aşağıda");
 this.verbDictionary.set("none", "hiçbiri");
 this.verbDictionary.set("nor", "ne de");
 this.verbDictionary.set("more", "daha fazla");
 this.verbDictionary.set("most", "çoğu");
 this.verbDictionary.set("long", "uzun");
 this.verbDictionary.set("need", "ihtiyaç");
 this.verbDictionary.set("Mr.", "Bay");
 this.verbDictionary.set("thought", "düşünce");
 this.verbDictionary.set("lot", "çok");
 this.verbDictionary.set("same", "aynı");
 this.verbDictionary.set("old", "eski");
 this.verbDictionary.set("word", "kelime");
 this.verbDictionary.set("course", "tabii ki");
 this.verbDictionary.set("life", "hayat");
 this.verbDictionary.set("side", "yan");
 this.verbDictionary.set("god", "tanrı");
 this.verbDictionary.set("week", "hafta");
 this.verbDictionary.set("family", "aile");
 this.verbDictionary.set("ever", "her zaman");
 this.verbDictionary.set("talk", "konuşma");
 this.verbDictionary.set("state", "durum");
 this.verbDictionary.set("set", "ayarla");
 this.verbDictionary.set("system", "sistem");
 this.verbDictionary.set("keep", "sakla");
 this.verbDictionary.set("try", "denemek");
 this.verbDictionary.set("change", "değişiklik");
 this.verbDictionary.set("general", "genel");
 this.verbDictionary.set("area", "alan");
 this.verbDictionary.set("believe", "inanmak");
 this.verbDictionary.set("young", "genç");
 this.verbDictionary.set("power", "güç");
 this.verbDictionary.set("almost", "neredeyse");
 this.verbDictionary.set("start", "başla");
 this.verbDictionary.set("person", "kişi");
 this.verbDictionary.set("become", "olmak");
 
 this.verbDictionary.set("local", "yerel");
 this.verbDictionary.set("run", "koşmak");
 this.verbDictionary.set("anyway", "neyse ki");
 this.verbDictionary.set("full", "tam");
 this.verbDictionary.set("office", "ofis");
 this.verbDictionary.set("live", "canlı");
 this.verbDictionary.set("development", "gelişim");
 this.verbDictionary.set("level", "seviye");
 this.verbDictionary.set("understand", "anlamak");
 this.verbDictionary.set("boy", "erkek çocuk");
 this.verbDictionary.set("research", "araştırma");
 this.verbDictionary.set("light", "ışık");
 this.verbDictionary.set("data", "veri");
 this.verbDictionary.set("wait", "bekle");
 this.verbDictionary.set("road", "yol");
 this.verbDictionary.set("particular", "özellikle");
 this.verbDictionary.set("paper", "kağıt");
 this.verbDictionary.set("view", "görünüm");
 this.verbDictionary.set("major", "büyük");
 this.verbDictionary.set("deal", "anlaşma");
 this.verbDictionary.set("news", "haber");
 this.verbDictionary.set("future", "gelecek");
 this.verbDictionary.set("death", "ölüm");
 this.verbDictionary.set("figure", "şekil");
 this.verbDictionary.set("land", "arazi");
 this.verbDictionary.set("process", "proses");
 this.verbDictionary.set("meeting", "toplantı");
 this.verbDictionary.set("seem", "görünmek");
 this.verbDictionary.set("interesting", "ilginç");
 this.verbDictionary.set("private", "özel");
 this.verbDictionary.set("easy", "kolay");
 this.verbDictionary.set("month", "ay");
 this.verbDictionary.set("evidence", "kanıt");
 this.verbDictionary.set("total", "toplam");
 this.verbDictionary.set("indeed", "gerçekten");
 this.verbDictionary.set("strong", "güçlü");
 this.verbDictionary.set("stage", "aşama");
 this.verbDictionary.set("committee", "komite");
 this.verbDictionary.set("tax", "vergi");
 this.verbDictionary.set("listen", "dinle");
 this.verbDictionary.set("likely", "muhtemelen");
 this.verbDictionary.set("sit", "otur");
 this.verbDictionary.set("feeling", "duygu");
 this.verbDictionary.set("voice", "ses");
 this.verbDictionary.set("poor", "fakir");
 this.verbDictionary.set("self", "kendisi");
 this.verbDictionary.set("chance", "şans");
 this.verbDictionary.set("speak", "konuş");
 this.verbDictionary.set("earlier", "daha önce");
 this.verbDictionary.set("evening", "akşam");
 
 this.verbDictionary.set("hello", "merhaba");
 this.verbDictionary.set("hospital", "hastane");
 this.verbDictionary.set("simply", "basitçe");
 this.verbDictionary.set("walk", "yürü");
 this.verbDictionary.set("hit", "vurmak");
 this.verbDictionary.set("recent", "son");
 this.verbDictionary.set("final", "son");
 this.verbDictionary.set("beginning", "başlangıç");
 this.verbDictionary.set("attention", "dikkat");
 this.verbDictionary.set("security", "güvenlik");
 this.verbDictionary.set("send", "gönder");
 this.verbDictionary.set("dog", "köpek");
 this.verbDictionary.set("degree", "derece");
 this.verbDictionary.set("dear", "sevgili");
 this.verbDictionary.set("date", "tarih");
 this.verbDictionary.set("normal", "normal");
 this.verbDictionary.set("blue", "mavi");
 this.verbDictionary.set("material", "malzeme");
 this.verbDictionary.set("choice", "seçenek");
 this.verbDictionary.set("cover", "kapak");
 this.verbDictionary.set("afternoon", "öğleden sonra");
 this.verbDictionary.set("science", "bilim");
 this.verbDictionary.set("movement", "hareket");
 this.verbDictionary.set("expect", "bekle");
 this.verbDictionary.set("capital", "başkent");
 this.verbDictionary.set("economy", "ekonomi");
 this.verbDictionary.set("Christmas", "Noel");
 this.verbDictionary.set("fast", "hızlı");
 this.verbDictionary.set("continue", "devam et");
 this.verbDictionary.set("earth", "dünya");
 this.verbDictionary.set("organisation", "organizasyon");
 this.verbDictionary.set("wall", "duvar");
 this.verbDictionary.set("property", "mülkiyet");
 this.verbDictionary.set("activity", "etkinlik");
 this.verbDictionary.set("note", "not");
 this.verbDictionary.set("treatment", "tedavi");
 this.verbDictionary.set("station", "istasyon");
 this.verbDictionary.set("teacher", "öğretmen");
 this.verbDictionary.set("forget", "unut");
 this.verbDictionary.set("although", "gerçi");
 this.verbDictionary.set("past", "geçmiş");
 this.verbDictionary.set("himself", "kendi");
 this.verbDictionary.set("seven", "yedi");
 this.verbDictionary.set("eight", "sekiz");
 this.verbDictionary.set("along", "boyunca");
 this.verbDictionary.set("round", "etrafında");
 this.verbDictionary.set("several", "birkaç");
 this.verbDictionary.set("someone", "birisi");
 this.verbDictionary.set("whatever", "her neyse");
 this.verbDictionary.set("among", "arasında");
 
 this.verbDictionary.set("across", "karşısına");
 this.verbDictionary.set("behind", "arkasında");
 this.verbDictionary.set("million", "milyon");
 this.verbDictionary.set("outside", "dışında");
 this.verbDictionary.set("nine", "dokuz");
 this.verbDictionary.set("thousand", "bin");
 this.verbDictionary.set("shall", "olmalı");
 this.verbDictionary.set("myself", "kendim");
 this.verbDictionary.set("themselves", "kendileri");
 this.verbDictionary.set("itself", "kendisi");
 this.verbDictionary.set("somebody", "birisi");
 this.verbDictionary.set("upon", "üzerinde");
 this.verbDictionary.set("thirty", "otuz");
 this.verbDictionary.set("third", "üçüncü");
 this.verbDictionary.set("above", "yukarıda");
 this.verbDictionary.set("therefore", "bu nedenle");
 this.verbDictionary.set("everybody", "herkes");
 this.verbDictionary.set("towards", "doğru");
 this.verbDictionary.set("thus", "böylece");
 this.verbDictionary.set("everyone", "herkes");
 this.verbDictionary.set("near", "yakın");
 this.verbDictionary.set("inside", "içinde");
 this.verbDictionary.set("nineteen", "on dokuz");
 this.verbDictionary.set("yourself", "kendin");
 this.verbDictionary.set("fifty", "elli");
 this.verbDictionary.set("whose", "kimin");
 this.verbDictionary.set("anyone", "herhangi birisi");
 this.verbDictionary.set("per", "her bir");
 this.verbDictionary.set("except", "hariç");
 this.verbDictionary.set("take", "almak");
 this.verbDictionary.set("make", "yapmak");
 this.verbDictionary.set("year", "yıl");
 this.verbDictionary.set("look", "bakmak");
 this.verbDictionary.set("thing", "şey");
 this.verbDictionary.set("man", "adam");
 this.verbDictionary.set("put", "koymak");
 this.verbDictionary.set("let", "bırakmak");
 this.verbDictionary.set("day", "gün");
 this.verbDictionary.set("never", "asla");
 this.verbDictionary.set("night", "gece");
 this.verbDictionary.set("left", "sol");
 this.verbDictionary.set("found", "bulmak");
 this.verbDictionary.set("high", "yüksek");
 this.verbDictionary.set("help", "yardım etmek");
 this.verbDictionary.set("maybe", "belki");
 this.verbDictionary.set("far", "uzak");
 this.verbDictionary.set("case", "durum");
 this.verbDictionary.set("whole", "bütün");
 this.verbDictionary.set("today", "bugün");
 this.verbDictionary.set("sorry", "üzgünüm");
 
 this.verbDictionary.set("show", "göstermek");
 this.verbDictionary.set("able", "yetenekli");
 this.verbDictionary.set("together", "birlikte");
 this.verbDictionary.set("order", "sıra");
 this.verbDictionary.set("head", "baş");
 this.verbDictionary.set("least", "en az");
 this.verbDictionary.set("read", "okumak");
 this.verbDictionary.set("morning", "sabah");
 this.verbDictionary.set("car", "araba");
 this.verbDictionary.set("city", "şehir");
 this.verbDictionary.set("possible", "mümkün");
 this.verbDictionary.set("cause", "sebep olmak");
 this.verbDictionary.set("present", "şu anki");
 this.verbDictionary.set("leave", "ayrılmak");
 this.verbDictionary.set("service", "hizmet");
 this.verbDictionary.set("stuff", "şey");
 this.verbDictionary.set("idea", "fikir");
 this.verbDictionary.set("line", "çizgi");
 this.verbDictionary.set("guess", "tahmin");
 this.verbDictionary.set("reason", "neden");
 this.verbDictionary.set("black", "siyah");
 this.verbDictionary.set("human", "insan");
 this.verbDictionary.set("university", "üniversite");
 this.verbDictionary.set("body", "vücut");
 this.verbDictionary.set("act", "hareket etmek");
 this.verbDictionary.set("hope", "umut");
 this.verbDictionary.set("child", "çocuk");
 this.verbDictionary.set("interest", "ilgi");
 this.verbDictionary.set("air", "hava");
 this.verbDictionary.set("Mrs.", "Bayan");
 this.verbDictionary.set("living", "yaşayan");
 this.verbDictionary.set("difficult", "zor");
 this.verbDictionary.set("town", "kasaba");
 this.verbDictionary.set("music", "müzik");
 this.verbDictionary.set("health", "sağlık");
 this.verbDictionary.set("buy", "satın almak");
 this.verbDictionary.set("certainly", "kesinlikle");
 this.verbDictionary.set("type", "tür");
 this.verbDictionary.set("street", "sokak");
 this.verbDictionary.set("effect", "etki");
 this.verbDictionary.set("subject", "konu");
 this.verbDictionary.set("college", "kolej");
 this.verbDictionary.set("red", "kırmızı");
 this.verbDictionary.set("hour", "saat");
 this.verbDictionary.set("provide", "sağlamak");
 this.verbDictionary.set("watch", "izlemek");
 this.verbDictionary.set("staff", "personel");
 this.verbDictionary.set("board", "tahta");
 this.verbDictionary.set("husband", "eş");
 this.verbDictionary.set("individual", "birey");
 this.verbDictionary.set("similar", "benzer");
 this.verbDictionary.set("doctor", "doktor");
 this.verbDictionary.set("yesterday", "dün");
 this.verbDictionary.set("nature", "doğa");
 this.verbDictionary.set("increase", "artış");
 this.verbDictionary.set("Dr", "Dr");
 this.verbDictionary.set("bed", "yatak");
 this.verbDictionary.set("fire", "ateş");
 this.verbDictionary.set("baby", "bebek");
 this.verbDictionary.set("cold", "soğuk");
 this.verbDictionary.set("central", "merkezi");
 this.verbDictionary.set("throat", "boğaz");
 this.verbDictionary.set("eat", "yemek");
 this.verbDictionary.set("learn", "öğrenmek");
 this.verbDictionary.set("price", "fiyat");
 this.verbDictionary.set("foreign", "yabancı");
 this.verbDictionary.set("lead", "liderlik etmek");
 this.verbDictionary.set("analysis", "analiz");
 this.verbDictionary.set("post", "gönderi");
 this.verbDictionary.set("fun", "eğlence");
 this.verbDictionary.set("financial", "mali");
 this.verbDictionary.set("ahead", "önünde");
 this.verbDictionary.set("tonight", "bu gece");
 this.verbDictionary.set("lower", "düşük");
 this.verbDictionary.set("current", "güncel");
 this.verbDictionary.set("recently", "son zamanlarda");
 this.verbDictionary.set("model", "model");
 this.verbDictionary.set("population", "nüfus");
 this.verbDictionary.set("funny", "komik");
 this.verbDictionary.set("fish", "balık");
 this.verbDictionary.set("clearly", "açıkça");
 this.verbDictionary.set("share", "paylaşmak");
 this.verbDictionary.set("doubt", "şüphe");
 this.verbDictionary.set("wide", "geniş");
 this.verbDictionary.set("step", "adım");
 this.verbDictionary.set("income", "gelir");
 this.verbDictionary.set("drink", "içmek");
 this.verbDictionary.set("authority", "otorite");
 this.verbDictionary.set("film", "film");
 this.verbDictionary.set("completely", "tamamen");
 this.verbDictionary.set("worry", "endişe");
 this.verbDictionary.set("generally", "genellikle");
 this.verbDictionary.set("page", "sayfa");
 this.verbDictionary.set("average", "ortalama");
 this.verbDictionary.set("respect", "saygı");
 this.verbDictionary.set("structure", "yapı");
 this.verbDictionary.set("club", "kulüp");
 this.verbDictionary.set("purpose", "amaç");
 this.verbDictionary.set("specific", "belirli");
 
 
 
 
 
   }


   get2(){
 
    this.userInput2="";
    this.isTranslationCorrect2=false;
    // Rastgele bir kelime seçme
let keys2 = Array.from(this.verbDictionary2.keys());
 this.randomKey2 = keys2[Math.floor(Math.random() * keys2.length)];

// Seçilen kelimenin Türkçe karşılığını alma
this.turkishEquivalent2 = this.verbDictionary2.get(this.randomKey2);

// Sonucu ekrana basma
console.log("İngilizce:", this.randomKey2);
console.log("Türkçe:", this.turkishEquivalent2);
  }

  showWord2(){
    this.userInput2=this.randomKey2;
    this.isTranslationCorrect2=true;

  }
  hint2(){
    this.userInput2=this.randomKey2.substring(0,2);
    
  }

  del2(){
 
    this.verbDictionary2.delete(this.randomKey2);
    console.log("Silindi:", this.randomKey2);
    this.get2();
    

  }
   load2(){
    
    
      this.verbDictionary2.set("the", "o");
  this.verbDictionary2.set("and", "ve");
  this.verbDictionary2.set("of", "nin");
  this.verbDictionary2.set("to", "e");
  this.verbDictionary2.set("a", "bir");
  this.verbDictionary2.set("I", "Ben");
  this.verbDictionary2.set("in", "içinde");
  this.verbDictionary2.set("you", "sen");
  this.verbDictionary2.set("that", "o");
  this.verbDictionary2.set("it", "o");
  this.verbDictionary2.set("for", "için");
  this.verbDictionary2.set("he", "o");
  this.verbDictionary2.set("on", "üzerinde");
  this.verbDictionary2.set("we", "biz");
  this.verbDictionary2.set("they", "onlar");
  this.verbDictionary2.set("be", "olmak");
  this.verbDictionary2.set("with", "ile");
  this.verbDictionary2.set("this", "bu");
  this.verbDictionary2.set("have", "sahip olmak");
  this.verbDictionary2.set("but", "ama");
  this.verbDictionary2.set("as", "olarak");
  this.verbDictionary2.set("not", "değil");
  this.verbDictionary2.set("at", "de");
  this.verbDictionary2.set("what", "ne");
  this.verbDictionary2.set("so", "bu yüzden");
  this.verbDictionary2.set("there", "orada");
  this.verbDictionary2.set("or", "veya");
  this.verbDictionary2.set("one", "bir");
  this.verbDictionary2.set("by", "tarafından");
  this.verbDictionary2.set("from", "den");
  this.verbDictionary2.set("all", "tüm");
  this.verbDictionary2.set("she", "o");
  this.verbDictionary2.set("no", "hayır");
  this.verbDictionary2.set("his", "onun");
  this.verbDictionary2.set("do", "yapmak");
  this.verbDictionary2.set("can", "yapabilir");
  this.verbDictionary2.set("if", "eğer");
  this.verbDictionary2.set("about", "hakkında");
  this.verbDictionary2.set("my", "benim");
  this.verbDictionary2.set("her", "onun");
  this.verbDictionary2.set("know", "bilmek");
  this.verbDictionary2.set("like", "gibi");
  this.verbDictionary2.set("well", "iyi");
  this.verbDictionary2.set("just", "sadece");
  this.verbDictionary2.set("think", "düşünmek");
  this.verbDictionary2.set("right", "doğru");
  this.verbDictionary2.set("then", "sonra");
  this.verbDictionary2.set("now", "şimdi");
  this.verbDictionary2.set("get", "almak");
  this.verbDictionary2.set("time", "zaman");
  this.verbDictionary2.set("again", "tekrar");
  this.verbDictionary2.set("own", "kendi");
  this.verbDictionary2.set("quite", "oldukça");
  this.verbDictionary2.set("give", "vermek");
  this.verbDictionary2.set("home", "ev");
  this.verbDictionary2.set("tell", "söylemek");
  this.verbDictionary2.set("world", "dünya");
  this.verbDictionary2.set("use", "kullanmak");
  this.verbDictionary2.set("always", "her zaman");
  this.verbDictionary2.set("great", "harika");
  this.verbDictionary2.set("problem", "sorun");
  this.verbDictionary2.set("love", "sevgi");
  this.verbDictionary2.set("name", "isim");
  this.verbDictionary2.set("percent", "yüzde");
  this.verbDictionary2.set("call", "aramak");
  this.verbDictionary2.set("water", "su");
  this.verbDictionary2.set("important", "önemli");
  this.verbDictionary2.set("country", "ülke");
  this.verbDictionary2.set("small", "küçük");
  this.verbDictionary2.set("feel", "hiss etmek");
  this.verbDictionary2.set("company", "şirket");
  this.verbDictionary2.set("perhaps", "belki");
  this.verbDictionary2.set("ago", "önce");
  this.verbDictionary2.set("hard", "zor");
  this.verbDictionary2.set("form", "form");
  this.verbDictionary2.set("party", "parti");
  this.verbDictionary2.set("means", "anlamına gelir");
  this.verbDictionary2.set("often", "sık sık");
  this.verbDictionary2.set("example", "örnek");
  this.verbDictionary2.set("play", "oynamak");
  this.verbDictionary2.set("fine", "iyi");
  this.verbDictionary2.set("certain", "kesin");
  this.verbDictionary2.set("turn", "dönmek");
  this.verbDictionary2.set("control", "kontrol etmek");
  this.verbDictionary2.set("sometimes", "bazen");
  this.verbDictionary2.set("political", "siyasi");
  this.verbDictionary2.set("top", "üst");
  this.verbDictionary2.set("story", "hikaye");
  this.verbDictionary2.set("door", "kapı");
  this.verbDictionary2.set("hear", "duymak");
  this.verbDictionary2.set("thinking", "düşünce");
  this.verbDictionary2.set("stay", "kalmak");
  this.verbDictionary2.set("market", "pazar");
  this.verbDictionary2.set("age", "yaş");
  this.verbDictionary2.set("support", "destek");
  this.verbDictionary2.set("clear", "net");
  this.verbDictionary2.set("police", "polis");
  this.verbDictionary2.set("department", "departman");
  this.verbDictionary2.set("table", "masa");
  this.verbDictionary2.set("experience", "deneyim");
  
  this.verbDictionary2.set("situation", "durum");
  this.verbDictionary2.set("alright", "tamam");
  this.verbDictionary2.set("court", "mahkeme");
  this.verbDictionary2.set("exactly", "tam olarak");
  this.verbDictionary2.set("main", "ana");
  this.verbDictionary2.set("rest", "geri kalan");
  this.verbDictionary2.set("son", "oğul");
  this.verbDictionary2.set("miss", "kaçırmak");
  this.verbDictionary2.set("hold", "tutmak");
  this.verbDictionary2.set("especially", "özellikle");
  this.verbDictionary2.set("thanks", "teşekkürler");
  this.verbDictionary2.set("middle", "orta");
  this.verbDictionary2.set("suppose", "varsaymak");
  this.verbDictionary2.set("field", "alan");
  this.verbDictionary2.set("game", "oyun");
  this.verbDictionary2.set("test", "test");
  this.verbDictionary2.set("dad", "baba");
  this.verbDictionary2.set("section", "bölüm");
  this.verbDictionary2.set("industry", "endüstri");
  this.verbDictionary2.set("sir", "efendi");
  this.verbDictionary2.set("finally", "sonunda");
  this.verbDictionary2.set("quality", "kalite");
  this.verbDictionary2.set("happen", "olmak");
  this.verbDictionary2.set("amount", "miktar");
  this.verbDictionary2.set("role", "rol");
  this.verbDictionary2.set("force", "kuvvet");
  this.verbDictionary2.set("difference", "fark");
  this.verbDictionary2.set("phone", "telefon");
  this.verbDictionary2.set("forward", "ileri");
  this.verbDictionary2.set("member", "üye");
  this.verbDictionary2.set("president", "başkan");
  this.verbDictionary2.set("production", "üretim");
  this.verbDictionary2.set("trouble", "sorun");
  this.verbDictionary2.set("management", "yönetim");
  this.verbDictionary2.set("account", "hesap");
  this.verbDictionary2.set("size", "boyut");
  this.verbDictionary2.set("hot", "sıcak");
  this.verbDictionary2.set("worth", "değer");
  this.verbDictionary2.set("simple", "basit");
  this.verbDictionary2.set("hell", "cehennem");
  this.verbDictionary2.set("approach", "yaklaşım");
  this.verbDictionary2.set("computer", "bilgisayar");
  this.verbDictionary2.set("straight", "düz");
  this.verbDictionary2.set("space", "uzay");
  this.verbDictionary2.set("colour", "renk");
  this.verbDictionary2.set("fall", "sonbahar");
  this.verbDictionary2.set("performance", "performans");
  this.verbDictionary2.set("culture", "kültür");
  this.verbDictionary2.set("pick", "seçmek");
  this.verbDictionary2.set("river", "nehir");
  this.verbDictionary2.set("kill", "öldürmek");
  this.verbDictionary2.set("follow", "takip etmek");
  this.verbDictionary2.set("function", "fonksiyon");
  this.verbDictionary2.set("practice", "pratik");
  this.verbDictionary2.set("former", "eski");
  this.verbDictionary2.set("sister", "kız kardeş");
  this.verbDictionary2.set("absolutely", "kesinlikle");
  this.verbDictionary2.set("somewhere", "bir yerlerde");
  this.verbDictionary2.set("include", "içermek");
  this.verbDictionary2.set("Sunday", "Pazar");
  this.verbDictionary2.set("television", "televizyon");
  this.verbDictionary2.set("western", "batı");
  this.verbDictionary2.set("opportunity", "fırsat");
  this.verbDictionary2.set("key", "anahtar");
  this.verbDictionary2.set("series", "dizi");
  this.verbDictionary2.set("born", "doğmak");
  this.verbDictionary2.set("park", "park");
  this.verbDictionary2.set("response", "tepki");
  this.verbDictionary2.set("style", "stil");
  this.verbDictionary2.set("hall", "salon");
  this.verbDictionary2.set("which", "hangi");
  this.verbDictionary2.set("up", "yukarı");
  this.verbDictionary2.set("out", "dışarı");
  this.verbDictionary2.set("would", "olurdu");
  this.verbDictionary2.set("when", "ne zaman");
  this.verbDictionary2.set("your", "senin");
  this.verbDictionary2.set("will", "olacak");
  this.verbDictionary2.set("their", "onların");
  this.verbDictionary2.set("who", "kim");
  this.verbDictionary2.set("some", "bazı");
  this.verbDictionary2.set("two", "iki");
  this.verbDictionary2.set("because", "çünkü");
  this.verbDictionary2.set("how", "nasıl");
  this.verbDictionary2.set("other", "diğer");
  this.verbDictionary2.set("could", "olabilir");
  this.verbDictionary2.set("our", "bizim");
  this.verbDictionary2.set("into", "içine");
  this.verbDictionary2.set("these", "bunlar");
  this.verbDictionary2.set("than", "daha");
  this.verbDictionary2.set("any", "herhangi");
  this.verbDictionary2.set("where", "nerede");
  this.verbDictionary2.set("over", "üzerinde");
  this.verbDictionary2.set("back", "geri");
  this.verbDictionary2.set("first", "ilk");
  this.verbDictionary2.set("much", "çok");
  this.verbDictionary2.set("down", "aşağı");
  this.verbDictionary2.set("its", "onun");
  this.verbDictionary2.set("should", "malı");
  this.verbDictionary2.set("after", "sonra");
  this.verbDictionary2.set("those", "onlar");
  
  
  this.verbDictionary2.set("may", "olabilir");
  this.verbDictionary2.set("something", "bir şey");
  this.verbDictionary2.set("three", "üç");
  this.verbDictionary2.set("little", "az");
  this.verbDictionary2.set("many", "birçok");
  this.verbDictionary2.set("why", "neden");
  this.verbDictionary2.set("before", "önce");
  this.verbDictionary2.set("such", "böyle");
  this.verbDictionary2.set("off", "kapalı");
  this.verbDictionary2.set("through", "aracılığıyla");
  this.verbDictionary2.set("go", "gitmek");
  this.verbDictionary2.set("yes", "evet");
  this.verbDictionary2.set("very", "çok");
  this.verbDictionary2.set("see", "görmek");
  this.verbDictionary2.set("people", "insanlar");
  this.verbDictionary2.set("here", "burada");
  this.verbDictionary2.set("good", "iyi");
  this.verbDictionary2.set("only", "sadece");
  this.verbDictionary2.set("really", "gerçekten");
  this.verbDictionary2.set("say", "demek");
  this.verbDictionary2.set("kind", "tür");
  this.verbDictionary2.set("actually", "aslında");
  this.verbDictionary2.set("sort", "sıralama");
  this.verbDictionary2.set("government", "hükümet");
  this.verbDictionary2.set("house", "ev");
  this.verbDictionary2.set("find", "bulmak");
  this.verbDictionary2.set("place", "yer");
  this.verbDictionary2.set("different", "farklı");
  this.verbDictionary2.set("part", "bölüm");
  this.verbDictionary2.set("sure", "emin");
  this.verbDictionary2.set("real", "gerçek");
  this.verbDictionary2.set("best", "en iyi");
  this.verbDictionary2.set("laugh", "gülmek");
  this.verbDictionary2.set("room", "oda");
  this.verbDictionary2.set("remember", "hatırlamak");
  this.verbDictionary2.set("nice", "hoş");
  this.verbDictionary2.set("rather", "tercihen");
  this.verbDictionary2.set("public", "genel");
  this.verbDictionary2.set("mother", "anne");
  this.verbDictionary2.set("less", "daha az");
  this.verbDictionary2.set("care", "önem vermek");
  this.verbDictionary2.set("ask", "sormak");
  this.verbDictionary2.set("social", "sosyal");
  this.verbDictionary2.set("national", "ulusal");
  this.verbDictionary2.set("book", "kitap");
  this.verbDictionary2.set("father", "baba");
  this.verbDictionary2.set("bad", "kötü");
  this.verbDictionary2.set("war", "savaş");
  this.verbDictionary2.set("large", "büyük");
  this.verbDictionary2.set("food", "yiyecek");
  this.verbDictionary2.set("moment", "an");
  this.verbDictionary2.set("sense", "anlam");
  this.verbDictionary2.set("law", "kanun");
  this.verbDictionary2.set("programme", "program");
  this.verbDictionary2.set("free", "ücretsiz");
  this.verbDictionary2.set("front", "ön");
  this.verbDictionary2.set("language", "dil");
  this.verbDictionary2.set("study", "çalışma");
  this.verbDictionary2.set("white", "beyaz");
  this.verbDictionary2.set("late", "geç");
  this.verbDictionary2.set("cut", "kesmek");
  this.verbDictionary2.set("south", "güney");
  this.verbDictionary2.set("report", "rapor");
  this.verbDictionary2.set("soon", "yakında");
  this.verbDictionary2.set("usually", "genellikle");
  this.verbDictionary2.set("bring", "getirmek");
  this.verbDictionary2.set("society", "toplum");
  this.verbDictionary2.set("history", "tarih");
  this.verbDictionary2.set("couple", "çift");
  this.verbDictionary2.set("available", "müsait");
  this.verbDictionary2.set("mum", "anne");
  this.verbDictionary2.set("church", "kilise");
  this.verbDictionary2.set("rate", "oran");
  this.verbDictionary2.set("council", "konsey");
  this.verbDictionary2.set("answer", "cevap");
  this.verbDictionary2.set("common", "ortak");
  this.verbDictionary2.set("north", "kuzey");
  this.verbDictionary2.set("happy", "mutlu");
  this.verbDictionary2.set("building", "bina");
  this.verbDictionary2.set("instead", "bunun yerine");
  this.verbDictionary2.set("action", "hareket");
  this.verbDictionary2.set("personal", "kişisel");
  this.verbDictionary2.set("write", "yazmak");
  this.verbDictionary2.set("team", "takım");
  this.verbDictionary2.set("heart", "kalp");
  this.verbDictionary2.set("value", "değer");
  this.verbDictionary2.set("issue", "sorun");
  this.verbDictionary2.set("various", "çeşitli");
  this.verbDictionary2.set("alone", "yalnız");
  this.verbDictionary2.set("letter", "mektup");
  this.verbDictionary2.set("range", "aralık");
  this.verbDictionary2.set("ground", "zemin");
  this.verbDictionary2.set("reading", "okuma");
  this.verbDictionary2.set("tomorrow", "yarın");
  this.verbDictionary2.set("due", "nedeniyle");
  this.verbDictionary2.set("knowledge", "bilgi");
  this.verbDictionary2.set("brother", "erkek kardeş");
  
  this.verbDictionary2.set("decision", "karar");
  this.verbDictionary2.set("beautiful", "güzel");
  this.verbDictionary2.set("standard", "standart");
  this.verbDictionary2.set("record", "kayıt");
  this.verbDictionary2.set("ball", "top");
  this.verbDictionary2.set("piece", "parça");
  this.verbDictionary2.set("interested", "ilgili");
  this.verbDictionary2.set("natural", "doğal");
  this.verbDictionary2.set("agree", "katılmak");
  this.verbDictionary2.set("modern", "modern");
  this.verbDictionary2.set("student", "öğrenci");
  this.verbDictionary2.set("summer", "yaz");
  this.verbDictionary2.set("pressure", "baskı");
  this.verbDictionary2.set("picture", "resim");
  this.verbDictionary2.set("relationship", "ilişki");
  this.verbDictionary2.set("dark", "karanlık");
  this.verbDictionary2.set("drive", "sürmek");
  this.verbDictionary2.set("visit", "ziyaret etmek");
  this.verbDictionary2.set("green", "yeşil");
  this.verbDictionary2.set("teaching", "öğretim");
  this.verbDictionary2.set("hotel", "otel");
  this.verbDictionary2.set("truth", "gerçek");
  this.verbDictionary2.set("design", "tasarım");
  this.verbDictionary2.set("wonder", "merak etmek");
  this.verbDictionary2.set("dinner", "akşam yemeği");
  this.verbDictionary2.set("medical", "medikal");
  this.verbDictionary2.set("fair", "adil");
  this.verbDictionary2.set("radio", "radyo");
  this.verbDictionary2.set("legal", "hukuki");
  this.verbDictionary2.set("pass", "geçmek");
  this.verbDictionary2.set("nearly", "neredeyse");
  this.verbDictionary2.set("daughter", "kız");
  this.verbDictionary2.set("trust", "güven");
  this.verbDictionary2.set("window", "pencere");
  this.verbDictionary2.set("carry", "taşımak");
  this.verbDictionary2.set("rights", "haklar");
  this.verbDictionary2.set("fight", "kavga");
  this.verbDictionary2.set("environment", "çevre");
  this.verbDictionary2.set("cool", "serin");
  this.verbDictionary2.set("sex", "cinsiyet");
  this.verbDictionary2.set("eye", "göz");
  this.verbDictionary2.set("region", "bölge");
  this.verbDictionary2.set("still", "hala");
  this.verbDictionary2.set("last", "son");
  this.verbDictionary2.set("being", "varlık");
  this.verbDictionary2.set("must", "meli");
  this.verbDictionary2.set("another", "başka");
  this.verbDictionary2.set("between", "arasında");
  this.verbDictionary2.set("might", "belki");
  this.verbDictionary2.set("both", "her ikisi de");
  this.verbDictionary2.set("five", "beş");
  this.verbDictionary2.set("four", "dört");
  this.verbDictionary2.set("around", "etrafında");
  
  this.verbDictionary2.set("while", "iken");
  this.verbDictionary2.set("each", "her biri");
  this.verbDictionary2.set("under", "altında");
  this.verbDictionary2.set("away", "uzakta");
  this.verbDictionary2.set("every", "her");
  this.verbDictionary2.set("next", "sonraki");
  this.verbDictionary2.set("anything", "herhangi bir şey");
  this.verbDictionary2.set("few", "birkaç");
  this.verbDictionary2.set("though", "rağmen");
  this.verbDictionary2.set("since", "beri");
  this.verbDictionary2.set("against", "karşı");
  this.verbDictionary2.set("second", "ikinci");
  this.verbDictionary2.set("nothing", "hiçbir şey");
  this.verbDictionary2.set("without", "olmadan");
  this.verbDictionary2.set("during", "sırasında");
  this.verbDictionary2.set("six", "altı");
  this.verbDictionary2.set("enough", "yeterli");
  this.verbDictionary2.set("once", "bir kere");
  this.verbDictionary2.set("however", "ancak");
  this.verbDictionary2.set("half", "yarım");
  this.verbDictionary2.set("yet", "henüz");
  this.verbDictionary2.set("whether", "olup olmadığı");
  this.verbDictionary2.set("everything", "her şey");
  this.verbDictionary2.set("until", "kadar");
  this.verbDictionary2.set("hundred", "yüz");
  this.verbDictionary2.set("within", "içinde");
  this.verbDictionary2.set("ten", "on");
  this.verbDictionary2.set("twenty", "yirmi");
  this.verbDictionary2.set("either", "ya");
  this.verbDictionary2.set("mean", "anlamına gelmek");
  this.verbDictionary2.set("come", "gelmek");
  this.verbDictionary2.set("also", "ayrıca");
  this.verbDictionary2.set("okay", "tamam");
  this.verbDictionary2.set("want", "istemek");
  this.verbDictionary2.set("way", "yol");
  this.verbDictionary2.set("even", "bile");
  this.verbDictionary2.set("new", "yeni");
  this.verbDictionary2.set("too", "çok");
  this.verbDictionary2.set("work", "çalışmak");
  this.verbDictionary2.set("point", "nokta");
  this.verbDictionary2.set("number", "sayı");
  this.verbDictionary2.set("school", "okul");
  this.verbDictionary2.set("end", "son");
  this.verbDictionary2.set("money", "para");
  this.verbDictionary2.set("better", "daha iyi");
  this.verbDictionary2.set("big", "büyük");
  this.verbDictionary2.set("probably", "muhtemelen");
  this.verbDictionary2.set("fact", "gerçek");
  this.verbDictionary2.set("bit", "biraz");
  this.verbDictionary2.set("later", "sonra");
  
  
  this.verbDictionary2.set("hand", "el");
  this.verbDictionary2.set("already", "zaten");
  this.verbDictionary2.set("mind", "akıl");
  this.verbDictionary2.set("thank", "teşekkür etmek");
  this.verbDictionary2.set("job", "iş");
  this.verbDictionary2.set("business", "iş");
  this.verbDictionary2.set("else", "başka");
  this.verbDictionary2.set("group", "grup");
  this.verbDictionary2.set("question", "soru");
  this.verbDictionary2.set("open", "açık");
  this.verbDictionary2.set("pretty", "güzel");
  this.verbDictionary2.set("matter", "önemli");
  this.verbDictionary2.set("information", "bilgi");
  this.verbDictionary2.set("hey", "hey");
  this.verbDictionary2.set("face", "yüz");
  this.verbDictionary2.set("early", "erken");
  this.verbDictionary2.set("please", "lütfen");
  this.verbDictionary2.set("pay", "ödemek");
  this.verbDictionary2.set("woman", "kadın");
  this.verbDictionary2.set("wrong", "yanlış");
  this.verbDictionary2.set("further", "daha fazla");
  this.verbDictionary2.set("move", "hareket etmek");
  this.verbDictionary2.set("guy", "adam");
  this.verbDictionary2.set("girl", "kız");
  this.verbDictionary2.set("wife", "eş");
  this.verbDictionary2.set("education", "eğitim");
  this.verbDictionary2.set("close", "kapat");
  this.verbDictionary2.set("stop", "durmak");
  this.verbDictionary2.set("class", "sınıf");
  this.verbDictionary2.set("short", "kısa");
  this.verbDictionary2.set("community", "topluluk");
  this.verbDictionary2.set("cost", "maliyet");
  this.verbDictionary2.set("friend", "arkadaş");
  this.verbDictionary2.set("economic", "ekonomik");
  this.verbDictionary2.set("position", "pozisyon");
  this.verbDictionary2.set("period", "dönem");
  this.verbDictionary2.set("policy", "politika");
  this.verbDictionary2.set("special", "özel");
  this.verbDictionary2.set("centre", "merkez");
  this.verbDictionary2.set("low", "düşük");
  this.verbDictionary2.set("meet", "tanışmak");
  this.verbDictionary2.set("west", "batı");
  this.verbDictionary2.set("art", "sanat");
  this.verbDictionary2.set("century", "yüzyıl");
  this.verbDictionary2.set("dead", "ölü");
  this.verbDictionary2.set("particularly", "özellikle");
  this.verbDictionary2.set("hi", "merhaba");
  this.verbDictionary2.set("result", "sonuç");
  this.verbDictionary2.set("plan", "plan");
  this.verbDictionary2.set("ready", "hazır");
  
  this.verbDictionary2.set("sound", "ses");
  this.verbDictionary2.set("international", "uluslararası");
  this.verbDictionary2.set("necessary", "gerekli");
  this.verbDictionary2.set("training", "eğitim");
  this.verbDictionary2.set("ok", "tamam");
  this.verbDictionary2.set("according", "göre");
  this.verbDictionary2.set("single", "tek");
  this.verbDictionary2.set("term", "terim");
  this.verbDictionary2.set("stand", "durmak");
  this.verbDictionary2.set("hair", "saç");
  this.verbDictionary2.set("bank", "banka");
  this.verbDictionary2.set("obviously", "açıkça");
  this.verbDictionary2.set("east", "doğu");
  this.verbDictionary2.set("writing", "yazma");
  this.verbDictionary2.set("return", "geri dönme");
  this.verbDictionary2.set("break", "mola");
  this.verbDictionary2.set("project", "proje");
  this.verbDictionary2.set("minute", "dakika");
  this.verbDictionary2.set("check", "kontrol etmek");
  this.verbDictionary2.set("wish", "dilemek");
  this.verbDictionary2.set("serious", "ciddi");
  this.verbDictionary2.set("minister", "bakan");
  this.verbDictionary2.set("growth", "büyüme");
  this.verbDictionary2.set("blood", "kan");
  this.verbDictionary2.set("bill", "fatura");
  this.verbDictionary2.set("trade", "ticaret");
  this.verbDictionary2.set("list", "liste");
  this.verbDictionary2.set("basis", "temel");
  this.verbDictionary2.set("floor", "zemin");
  this.verbDictionary2.set("island", "ada");
  this.verbDictionary2.set("sign", "işaret");
  this.verbDictionary2.set("basic", "temel");
  this.verbDictionary2.set("military", "askeri");
  this.verbDictionary2.set("press", "basın");
  this.verbDictionary2.set("spend", "harcamak");
  this.verbDictionary2.set("consider", "düşünmek");
  this.verbDictionary2.set("sea", "deniz");
  this.verbDictionary2.set("complete", "tamamlamak");
  this.verbDictionary2.set("bye", "hoşça kal");
  this.verbDictionary2.set("theory", "teori");
  this.verbDictionary2.set("shot", "ateş");
  this.verbDictionary2.set("energy", "enerji");
  this.verbDictionary2.set("offer", "teklif");
  this.verbDictionary2.set("patients", "hastalar");
  this.verbDictionary2.set("significant", "önemli");
  this.verbDictionary2.set("deep", "derin");
  this.verbDictionary2.set("begin", "başlamak");
  this.verbDictionary2.set("quickly", "hızlıca");
  this.verbDictionary2.set("charge", "ücret");
  this.verbDictionary2.set("original", "orijinal");
  
  this.verbDictionary2.set("dollar", "dolar");
  this.verbDictionary2.set("square", "kare");
  this.verbDictionary2.set("direct", "doğrudan");
  this.verbDictionary2.set("forty", "kırk");
  this.verbDictionary2.set("nobody", "hiç kimse");
  this.verbDictionary2.set("unless", "eğer ki");
  this.verbDictionary2.set("mine", "benimki");
  this.verbDictionary2.set("anybody", "herhangi biri");
  this.verbDictionary2.set("till", "kadar");
  this.verbDictionary2.set("herself", "kendi");
  this.verbDictionary2.set("twelve", "on iki");
  this.verbDictionary2.set("fifteen", "on beş");
  this.verbDictionary2.set("beyond", "ötesinde");
  this.verbDictionary2.set("whom", "kimi");
  this.verbDictionary2.set("below", "aşağıda");
  this.verbDictionary2.set("none", "hiçbiri");
  this.verbDictionary2.set("nor", "ne de");
  this.verbDictionary2.set("more", "daha fazla");
  this.verbDictionary2.set("most", "çoğu");
  this.verbDictionary2.set("long", "uzun");
  this.verbDictionary2.set("need", "ihtiyaç");
  this.verbDictionary2.set("Mr.", "Bay");
  this.verbDictionary2.set("thought", "düşünce");
  this.verbDictionary2.set("lot", "çok");
  this.verbDictionary2.set("same", "aynı");
  this.verbDictionary2.set("old", "eski");
  this.verbDictionary2.set("word", "kelime");
  this.verbDictionary2.set("course", "tabii ki");
  this.verbDictionary2.set("life", "hayat");
  this.verbDictionary2.set("side", "yan");
  this.verbDictionary2.set("god", "tanrı");
  this.verbDictionary2.set("week", "hafta");
  this.verbDictionary2.set("family", "aile");
  this.verbDictionary2.set("ever", "her zaman");
  this.verbDictionary2.set("talk", "konuşma");
  this.verbDictionary2.set("state", "durum");
  this.verbDictionary2.set("set", "ayarla");
  this.verbDictionary2.set("system", "sistem");
  this.verbDictionary2.set("keep", "sakla");
  this.verbDictionary2.set("try", "denemek");
  this.verbDictionary2.set("change", "değişiklik");
  this.verbDictionary2.set("general", "genel");
  this.verbDictionary2.set("area", "alan");
  this.verbDictionary2.set("believe", "inanmak");
  this.verbDictionary2.set("young", "genç");
  this.verbDictionary2.set("power", "güç");
  this.verbDictionary2.set("almost", "neredeyse");
  this.verbDictionary2.set("start", "başla");
  this.verbDictionary2.set("person", "kişi");
  this.verbDictionary2.set("become", "olmak");
  
  this.verbDictionary2.set("local", "yerel");
  this.verbDictionary2.set("run", "koşmak");
  this.verbDictionary2.set("anyway", "neyse ki");
  this.verbDictionary2.set("full", "tam");
  this.verbDictionary2.set("office", "ofis");
  this.verbDictionary2.set("live", "canlı");
  this.verbDictionary2.set("development", "gelişim");
  this.verbDictionary2.set("level", "seviye");
  this.verbDictionary2.set("understand", "anlamak");
  this.verbDictionary2.set("boy", "erkek çocuk");
  this.verbDictionary2.set("research", "araştırma");
  this.verbDictionary2.set("light", "ışık");
  this.verbDictionary2.set("data", "veri");
  this.verbDictionary2.set("wait", "bekle");
  this.verbDictionary2.set("road", "yol");
  this.verbDictionary2.set("particular", "özellikle");
  this.verbDictionary2.set("paper", "kağıt");
  this.verbDictionary2.set("view", "görünüm");
  this.verbDictionary2.set("major", "büyük");
  this.verbDictionary2.set("deal", "anlaşma");
  this.verbDictionary2.set("news", "haber");
  this.verbDictionary2.set("future", "gelecek");
  this.verbDictionary2.set("death", "ölüm");
  this.verbDictionary2.set("figure", "şekil");
  this.verbDictionary2.set("land", "arazi");
  this.verbDictionary2.set("process", "proses");
  this.verbDictionary2.set("meeting", "toplantı");
  this.verbDictionary2.set("seem", "görünmek");
  this.verbDictionary2.set("interesting", "ilginç");
  this.verbDictionary2.set("private", "özel");
  this.verbDictionary2.set("easy", "kolay");
  this.verbDictionary2.set("month", "ay");
  this.verbDictionary2.set("evidence", "kanıt");
  this.verbDictionary2.set("total", "toplam");
  this.verbDictionary2.set("indeed", "gerçekten");
  this.verbDictionary2.set("strong", "güçlü");
  this.verbDictionary2.set("stage", "aşama");
  this.verbDictionary2.set("committee", "komite");
  this.verbDictionary2.set("tax", "vergi");
  this.verbDictionary2.set("listen", "dinle");
  this.verbDictionary2.set("likely", "muhtemelen");
  this.verbDictionary2.set("sit", "otur");
  this.verbDictionary2.set("feeling", "duygu");
  this.verbDictionary2.set("voice", "ses");
  this.verbDictionary2.set("poor", "fakir");
  this.verbDictionary2.set("self", "kendisi");
  this.verbDictionary2.set("chance", "şans");
  this.verbDictionary2.set("speak", "konuş");
  this.verbDictionary2.set("earlier", "daha önce");
  this.verbDictionary2.set("evening", "akşam");
  
  this.verbDictionary2.set("hello", "merhaba");
  this.verbDictionary2.set("hospital", "hastane");
  this.verbDictionary2.set("simply", "basitçe");
  this.verbDictionary2.set("walk", "yürü");
  this.verbDictionary2.set("hit", "vurmak");
  this.verbDictionary2.set("recent", "son");
  this.verbDictionary2.set("final", "son");
  this.verbDictionary2.set("beginning", "başlangıç");
  this.verbDictionary2.set("attention", "dikkat");
  this.verbDictionary2.set("security", "güvenlik");
  this.verbDictionary2.set("send", "gönder");
  this.verbDictionary2.set("dog", "köpek");
  this.verbDictionary2.set("degree", "derece");
  this.verbDictionary2.set("dear", "sevgili");
  this.verbDictionary2.set("date", "tarih");
  this.verbDictionary2.set("normal", "normal");
  this.verbDictionary2.set("blue", "mavi");
  this.verbDictionary2.set("material", "malzeme");
  this.verbDictionary2.set("choice", "seçenek");
  this.verbDictionary2.set("cover", "kapak");
  this.verbDictionary2.set("afternoon", "öğleden sonra");
  this.verbDictionary2.set("science", "bilim");
  this.verbDictionary2.set("movement", "hareket");
  this.verbDictionary2.set("expect", "bekle");
  this.verbDictionary2.set("capital", "başkent");
  this.verbDictionary2.set("economy", "ekonomi");
  this.verbDictionary2.set("Christmas", "Noel");
  this.verbDictionary2.set("fast", "hızlı");
  this.verbDictionary2.set("continue", "devam et");
  this.verbDictionary2.set("earth", "dünya");
  this.verbDictionary2.set("organisation", "organizasyon");
  this.verbDictionary2.set("wall", "duvar");
  this.verbDictionary2.set("property", "mülkiyet");
  this.verbDictionary2.set("activity", "etkinlik");
  this.verbDictionary2.set("note", "not");
  this.verbDictionary2.set("treatment", "tedavi");
  this.verbDictionary2.set("station", "istasyon");
  this.verbDictionary2.set("teacher", "öğretmen");
  this.verbDictionary2.set("forget", "unut");
  this.verbDictionary2.set("although", "gerçi");
  this.verbDictionary2.set("past", "geçmiş");
  this.verbDictionary2.set("himself", "kendi");
  this.verbDictionary2.set("seven", "yedi");
  this.verbDictionary2.set("eight", "sekiz");
  this.verbDictionary2.set("along", "boyunca");
  this.verbDictionary2.set("round", "etrafında");
  this.verbDictionary2.set("several", "birkaç");
  this.verbDictionary2.set("someone", "birisi");
  this.verbDictionary2.set("whatever", "her neyse");
  this.verbDictionary2.set("among", "arasında");
  
  this.verbDictionary2.set("across", "karşısına");
  this.verbDictionary2.set("behind", "arkasında");
  this.verbDictionary2.set("million", "milyon");
  this.verbDictionary2.set("outside", "dışında");
  this.verbDictionary2.set("nine", "dokuz");
  this.verbDictionary2.set("thousand", "bin");
  this.verbDictionary2.set("shall", "olmalı");
  this.verbDictionary2.set("myself", "kendim");
  this.verbDictionary2.set("themselves", "kendileri");
  this.verbDictionary2.set("itself", "kendisi");
  this.verbDictionary2.set("somebody", "birisi");
  this.verbDictionary2.set("upon", "üzerinde");
  this.verbDictionary2.set("thirty", "otuz");
  this.verbDictionary2.set("third", "üçüncü");
  this.verbDictionary2.set("above", "yukarıda");
  this.verbDictionary2.set("therefore", "bu nedenle");
  this.verbDictionary2.set("everybody", "herkes");
  this.verbDictionary2.set("towards", "doğru");
  this.verbDictionary2.set("thus", "böylece");
  this.verbDictionary2.set("everyone", "herkes");
  this.verbDictionary2.set("near", "yakın");
  this.verbDictionary2.set("inside", "içinde");
  this.verbDictionary2.set("nineteen", "on dokuz");
  this.verbDictionary2.set("yourself", "kendin");
  this.verbDictionary2.set("fifty", "elli");
  this.verbDictionary2.set("whose", "kimin");
  this.verbDictionary2.set("anyone", "herhangi birisi");
  this.verbDictionary2.set("per", "her bir");
  this.verbDictionary2.set("except", "hariç");
  this.verbDictionary2.set("take", "almak");
  this.verbDictionary2.set("make", "yapmak");
  this.verbDictionary2.set("year", "yıl");
  this.verbDictionary2.set("look", "bakmak");
  this.verbDictionary2.set("thing", "şey");
  this.verbDictionary2.set("man", "adam");
  this.verbDictionary2.set("put", "koymak");
  this.verbDictionary2.set("let", "bırakmak");
  this.verbDictionary2.set("day", "gün");
  this.verbDictionary2.set("never", "asla");
  this.verbDictionary2.set("night", "gece");
  this.verbDictionary2.set("left", "sol");
  this.verbDictionary2.set("found", "bulmak");
  this.verbDictionary2.set("high", "yüksek");
  this.verbDictionary2.set("help", "yardım etmek");
  this.verbDictionary2.set("maybe", "belki");
  this.verbDictionary2.set("far", "uzak");
  this.verbDictionary2.set("case", "durum");
  this.verbDictionary2.set("whole", "bütün");
  this.verbDictionary2.set("today", "bugün");
  this.verbDictionary2.set("sorry", "üzgünüm");
  
  this.verbDictionary2.set("show", "göstermek");
  this.verbDictionary2.set("able", "yetenekli");
  this.verbDictionary2.set("together", "birlikte");
  this.verbDictionary2.set("order", "sıra");
  this.verbDictionary2.set("head", "baş");
  this.verbDictionary2.set("least", "en az");
  this.verbDictionary2.set("read", "okumak");
  this.verbDictionary2.set("morning", "sabah");
  this.verbDictionary2.set("car", "araba");
  this.verbDictionary2.set("city", "şehir");
  this.verbDictionary2.set("possible", "mümkün");
  this.verbDictionary2.set("cause", "sebep olmak");
  this.verbDictionary2.set("present", "şu anki");
  this.verbDictionary2.set("leave", "ayrılmak");
  this.verbDictionary2.set("service", "hizmet");
  this.verbDictionary2.set("stuff", "şey");
  this.verbDictionary2.set("idea", "fikir");
  this.verbDictionary2.set("line", "çizgi");
  this.verbDictionary2.set("guess", "tahmin");
  this.verbDictionary2.set("reason", "neden");
  this.verbDictionary2.set("black", "siyah");
  this.verbDictionary2.set("human", "insan");
  this.verbDictionary2.set("university", "üniversite");
  this.verbDictionary2.set("body", "vücut");
  this.verbDictionary2.set("act", "hareket etmek");
  this.verbDictionary2.set("hope", "umut");
  this.verbDictionary2.set("child", "çocuk");
  this.verbDictionary2.set("interest", "ilgi");
  this.verbDictionary2.set("air", "hava");
  this.verbDictionary2.set("Mrs.", "Bayan");
  this.verbDictionary2.set("living", "yaşayan");
  this.verbDictionary2.set("difficult", "zor");
  this.verbDictionary2.set("town", "kasaba");
  this.verbDictionary2.set("music", "müzik");
  this.verbDictionary2.set("health", "sağlık");
  this.verbDictionary2.set("buy", "satın almak");
  this.verbDictionary2.set("certainly", "kesinlikle");
  this.verbDictionary2.set("type", "tür");
  this.verbDictionary2.set("street", "sokak");
  this.verbDictionary2.set("effect", "etki");
  this.verbDictionary2.set("subject", "konu");
  this.verbDictionary2.set("college", "kolej");
  this.verbDictionary2.set("red", "kırmızı");
  this.verbDictionary2.set("hour", "saat");
  this.verbDictionary2.set("provide", "sağlamak");
  this.verbDictionary2.set("watch", "izlemek");
  this.verbDictionary2.set("staff", "personel");
  this.verbDictionary2.set("board", "tahta");
  this.verbDictionary2.set("husband", "eş");
  this.verbDictionary2.set("individual", "birey");
  this.verbDictionary2.set("similar", "benzer");
  this.verbDictionary2.set("doctor", "doktor");
  this.verbDictionary2.set("yesterday", "dün");
  this.verbDictionary2.set("nature", "doğa");
  this.verbDictionary2.set("increase", "artış");
  this.verbDictionary2.set("Dr", "Dr");
  this.verbDictionary2.set("bed", "yatak");
  this.verbDictionary2.set("fire", "ateş");
  this.verbDictionary2.set("baby", "bebek");
  this.verbDictionary2.set("cold", "soğuk");
  this.verbDictionary2.set("central", "merkezi");
  this.verbDictionary2.set("throat", "boğaz");
  this.verbDictionary2.set("eat", "yemek");
  this.verbDictionary2.set("learn", "öğrenmek");
  this.verbDictionary2.set("price", "fiyat");
  this.verbDictionary2.set("foreign", "yabancı");
  this.verbDictionary2.set("lead", "liderlik etmek");
  this.verbDictionary2.set("analysis", "analiz");
  this.verbDictionary2.set("post", "gönderi");
  this.verbDictionary2.set("fun", "eğlence");
  this.verbDictionary2.set("financial", "mali");
  this.verbDictionary2.set("ahead", "önünde");
  this.verbDictionary2.set("tonight", "bu gece");
  this.verbDictionary2.set("lower", "düşük");
  this.verbDictionary2.set("current", "güncel");
  this.verbDictionary2.set("recently", "son zamanlarda");
  this.verbDictionary2.set("model", "model");
  this.verbDictionary2.set("population", "nüfus");
  this.verbDictionary2.set("funny", "komik");
  this.verbDictionary2.set("fish", "balık");
  this.verbDictionary2.set("clearly", "açıkça");
  this.verbDictionary2.set("share", "paylaşmak");
  this.verbDictionary2.set("doubt", "şüphe");
  this.verbDictionary2.set("wide", "geniş");
  this.verbDictionary2.set("step", "adım");
  this.verbDictionary2.set("income", "gelir");
  this.verbDictionary2.set("drink", "içmek");
  this.verbDictionary2.set("authority", "otorite");
  this.verbDictionary2.set("film", "film");
  this.verbDictionary2.set("completely", "tamamen");
  this.verbDictionary2.set("worry", "endişe");
  this.verbDictionary2.set("generally", "genellikle");
  this.verbDictionary2.set("page", "sayfa");
  this.verbDictionary2.set("average", "ortalama");
  this.verbDictionary2.set("respect", "saygı");
  this.verbDictionary2.set("structure", "yapı");
  this.verbDictionary2.set("club", "kulüp");
  this.verbDictionary2.set("purpose", "amaç");
  this.verbDictionary2.set("specific", "belirli");
   }


}
