import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { Subscription, interval, map, of, take, zip } from 'rxjs';
import { SynonymsService } from '../services/synonyms.service';
import { IrregularverbsService } from '../services/irregularverbs.service';
import { PhrasalverbsService } from '../services/phrasalverbs.service';

@Component({
  selector: 'app-english-turkish',
  templateUrl: './english-turkish.component.html',
  styleUrls: ['./english-turkish.component.css']
})
export class EnglishTurkishComponent implements OnInit {

  @ViewChild('userInputField', { static: false }) userInputField!: ElementRef;
@ViewChild('userInputEnField', { static: false }) userInputEnField!: ElementRef;
  verbDictionary = new Map();
  verbDictionary2 = new Map();
  
  randomKey:any;
  randomKey2:any;
  turkishEquivalent:any;
  turkishEquivalent2:any;
  autorandomKey:any="English";
  autoturkishEquivalent:any="Türkçe";
  selectedWaitTime: number = 5;
  private intervalSubscription: Subscription | undefined;
  userInput: string = ''; // Kullanıcının girdiği Türkçe kelime
  userInputEn: string = ''; // Kullanıcının girdiği İngilizce kelime
  isTranslationCorrect: boolean = false; // Türkçe kelimenin doğruluğu
  isTranslationCorrect2: boolean = false; // İngilizce kelimenin doğruluğu
 
  randomWord!: { word: string, synonyms: string[] };
  randomIrregularVerbWord!: { word: string, irregularVerb: string[] };
  randomPhrasalVerbWord!: { word: string, phrasalVerb: string};
 
 
   constructor(
    private synonymsService:SynonymsService, 
    private irregularVerbsService:IrregularverbsService,
    private phrasalVerbsService:PhrasalverbsService
    
    ) {
    
     
   }

   ngAfterViewInit() {
    // Artık this.userInputField kullanılabilir
    this.get2();
    this.get();
    
  }

 
   ngOnInit(): void {
     
     this.load();
     this.load2();
     
     
     this.getIrregularVerbWord();
     this.getSynonymsWord();
     this.getPhrasalVerbWord();
 
     this.startInterval();
     
     
   }
 inputFocus(){
  this.userInputField.nativeElement.focus();
 }
 inputEnFocus(){
  this.userInputEnField.nativeElement.focus();
 }
 
   checkTranslation() {
     // Kullanıcının girdiği  türkçe kelimeyi kontrol et
     this.isTranslationCorrect = this.userInput.toLowerCase() === this.turkishEquivalent.toLowerCase();
   }
   checkTranslation2() {
    // Kullanıcının girdiği ingilizce kelimeyi kontrol et
    this.isTranslationCorrect2 = this.userInputEn.toLowerCase() === this.randomKey2.toLowerCase();
  }
 
   ngOnDestroy() {
     this.stopInterval();
   }
 
   onChangeWaitTime(event: any) {
     this.selectedWaitTime = +event.target.value;
     this.restartInterval();
     
   }
 
 
    startInterval() {
     this.intervalSubscription = interval(this.selectedWaitTime * 1000).subscribe(() => {
       this.autoget();
       
     });
   }
 
   private stopInterval() {
     if (this.intervalSubscription) {
       this.intervalSubscription.unsubscribe();
     }
   }
 
   private restartInterval() {
     this.stopInterval();
     this.startInterval();
   }
 
   del(){
 
     this.verbDictionary.delete(this.randomKey);
     console.log("Silindi:", this.randomKey);
     this.get();
     this.inputFocus();
     
 
   }
 
   showWord(){
     this.userInput=this.turkishEquivalent;
     this.isTranslationCorrect=true;
     this.inputFocus();
     
 
   }
   hint(){
    this.userInput=this.turkishEquivalent.substring(0,2);
    this.inputFocus();
    
  }
 
   autoget=()=>{
 // Rastgele bir kelime seçme
 let keys = Array.from(this.verbDictionary.keys());
  this.autorandomKey = keys[Math.floor(Math.random() * keys.length)];
 
 // Seçilen kelimenin Türkçe karşılığını alma
 this.autoturkishEquivalent = this.verbDictionary.get(this.autorandomKey);
 


 
 
     
   }

   getSynonymsWord(){
    
    this.randomWord = this.synonymsService.getAllSynonymsForRandomWord();
    
   }

   getIrregularVerbWord(){
    
    this.randomIrregularVerbWord = this.irregularVerbsService.getAllIrregularVerbsForRandomWord();
    
   }

   getPhrasalVerbWord(){
    
    this.randomPhrasalVerbWord = this.phrasalVerbsService.getAllPhrasalVerbsForRandomWord();
    
   }

  
 
   get(){
    this.inputFocus();
     this.userInput="";
     this.isTranslationCorrect=false;
     // Rastgele bir kelime seçme
 let keys = Array.from(this.verbDictionary.keys());
  this.randomKey = keys[Math.floor(Math.random() * 5)];
 
 // Seçilen kelimenin Türkçe karşılığını alma
 this.turkishEquivalent = this.verbDictionary.get(this.randomKey);

 
 
 // Sonucu ekrana basma
 console.log("İngilizce:", this.randomKey);
 console.log("Türkçe:", this.turkishEquivalent);

 
   }
 
   
load(){
  this.verbDictionary.set("easy", "kolay");
this.verbDictionary.set("society", "toplum");
this.verbDictionary.set("option", "seçenek");
this.verbDictionary.set("offer", "teklif etmek");
this.verbDictionary.set("age", "yas");
this.verbDictionary.set("figure", "sekil");
this.verbDictionary.set("west", "bati");
this.verbDictionary.set("either", "ya");
this.verbDictionary.set("voice", "ses");
this.verbDictionary.set("among", "arasinda, içinde");
this.verbDictionary.set("across", "karsisinda");
this.verbDictionary.set("listen", "dinlemek");
this.verbDictionary.set("example", "örnek");
this.verbDictionary.set("majority", "çogunluk");
this.verbDictionary.set("victim", "kurban");
this.verbDictionary.set("interview", "röportaj");
this.verbDictionary.set("phone", "telefon");
this.verbDictionary.set("exactly", "kesinlikle");
this.verbDictionary.set("chair", "sandalye");
this.verbDictionary.set("value", "deger");
this.verbDictionary.set("when", "ne zaman");
this.verbDictionary.set("per", "basina, göre");
this.verbDictionary.set("issue", "sorun");
this.verbDictionary.set("zoo", "hayvanat bahçesi");
this.verbDictionary.set("sea", "deniz");
this.verbDictionary.set("provide", "saglamak");
this.verbDictionary.set("task", "görev");
this.verbDictionary.set("spring", "bahar");
this.verbDictionary.set("lead", "öncülük etmek");
this.verbDictionary.set("contain", "içermek");
this.verbDictionary.set("relate", "Iliski kurmak");
this.verbDictionary.set("anything", "bir seyi herhangi bir sey, hiçbir sey");
this.verbDictionary.set("unit", "ünite");
this.verbDictionary.set("protect", "korumak");
this.verbDictionary.set("american", "amerikan");
this.verbDictionary.set("over", "bitti");
this.verbDictionary.set("address", "adres");
this.verbDictionary.set("myself", "kendim");
this.verbDictionary.set("success", "basari");
this.verbDictionary.set("loss", "kayip");
this.verbDictionary.set("particular", "özel, belirli");
this.verbDictionary.set("anyway", "her halükârda");
this.verbDictionary.set("treatment", "tedavi");
this.verbDictionary.set("cover", "örtmek");
this.verbDictionary.set("him", "onu (erkek)");
this.verbDictionary.set("rest", "dinlenme");
this.verbDictionary.set("but", "fakat, ama, lakin");
this.verbDictionary.set("rule", "kural");
this.verbDictionary.set("through", "vasitasiyla");
this.verbDictionary.set("price", "fiyat");
this.verbDictionary.set("view", "görünüm");
this.verbDictionary.set("he", "o (erkek)");
this.verbDictionary.set("pick", "almak");
this.verbDictionary.set("off", "kapali");
this.verbDictionary.set("wind", "rüzgar");
this.verbDictionary.set("marriage", "evlilik");
this.verbDictionary.set("character", "karakter");
this.verbDictionary.set("risk", "risk");
this.verbDictionary.set("almost", "neredeyse, hemen hemen");
this.verbDictionary.set("for", "için");
this.verbDictionary.set("discussion", "tartisma");
this.verbDictionary.set("however", "ancak");
this.verbDictionary.set("politics", "siyaset");
this.verbDictionary.set("close", "kapatmak");
this.verbDictionary.set("type", "tip, tür, model");
this.verbDictionary.set("audience", "seyirci, izleyici");
this.verbDictionary.set("our", "bizim");
this.verbDictionary.set("goal", "hedef");
this.verbDictionary.set("determine", "belirlemek");
this.verbDictionary.set("can", "yapabilmek");
this.verbDictionary.set("game", "oyun");
this.verbDictionary.set("probably", "muhtemelen");
this.verbDictionary.set("traditional", "geleneksel");
this.verbDictionary.set("hang", "asmak");
this.verbDictionary.set("consider", "dikkate almak");
this.verbDictionary.set("such", "böyle");
this.verbDictionary.set("some", "bazi");
this.verbDictionary.set("bag", "sirt çantasi");
this.verbDictionary.set("common", "ortak");
this.verbDictionary.set("young", "genç");
this.verbDictionary.set("why", "niçin?");
this.verbDictionary.set("disease", "hastalik");
this.verbDictionary.set("hard", "zor");
this.verbDictionary.set("group", "grup");
this.verbDictionary.set("most", "çogu");
this.verbDictionary.set("discover", "kesfetmek");
this.verbDictionary.set("plan", "plan");
this.verbDictionary.set("as", "gibi, olarak");
this.verbDictionary.set("travel", "seyahat");
this.verbDictionary.set("suddenly", "aniden");
this.verbDictionary.set("really", "gerçekten");
this.verbDictionary.set("seem", "görünmek");
this.verbDictionary.set("name", "isim");
this.verbDictionary.set("data", "veri");
this.verbDictionary.set("top", "üst");
this.verbDictionary.set("ground", "zemin");
this.verbDictionary.set("table", "masa, tablo");
this.verbDictionary.set("work", "çalismak");
this.verbDictionary.set("dream", "rüya");
this.verbDictionary.set("prepare", "hazirlamak");
this.verbDictionary.set("condition", "sart");
this.verbDictionary.set("might", "belki");
this.verbDictionary.set("card", "kart");
this.verbDictionary.set("above", "yukarida");
this.verbDictionary.set("thought", "düsündü");
this.verbDictionary.set("wonder", "merak etmek, sasmak");
this.verbDictionary.set("modern", "modern");
this.verbDictionary.set("all", "her sey, tüm, bütün");
this.verbDictionary.set("student", "ögrenci");
this.verbDictionary.set("capital", "baskent");
this.verbDictionary.set("second", "ikinci");
this.verbDictionary.set("poor", "fakir");
this.verbDictionary.set("on", "üzerinde");
this.verbDictionary.set("conference", "konferans");
this.verbDictionary.set("because", "çünkü");
this.verbDictionary.set("away", "uzak, uzakta");
this.verbDictionary.set("summer", "yaz");
this.verbDictionary.set("speech", "konusma");
this.verbDictionary.set("environment", "çevre");
this.verbDictionary.set("dead", "ölü");
this.verbDictionary.set("store", "magaza");
this.verbDictionary.set("bring", "getirmek");
this.verbDictionary.set("no", "hayir");
this.verbDictionary.set("money", "para");
this.verbDictionary.set("them", "onlari");
this.verbDictionary.set("think", "düsünmek");
this.verbDictionary.set("help", "yardim");
this.verbDictionary.set("once", "bir zamanlar");
this.verbDictionary.set("next", "sonraki");
this.verbDictionary.set("current", "su andaki");
this.verbDictionary.set("wall", "duvar");
this.verbDictionary.set("environmental", "çevreci");
this.verbDictionary.set("us", "bize");
this.verbDictionary.set("wrong", "yanlis");
this.verbDictionary.set("animal", "hayvan");
this.verbDictionary.set("indicate", "belirtmek");
this.verbDictionary.set("movement", "hareket");
this.verbDictionary.set("professional", "profesyonel");
this.verbDictionary.set("article", "makale, yazi");
this.verbDictionary.set("indeed", "aslinda");
this.verbDictionary.set("far", "uzak");
this.verbDictionary.set("business", "is");
this.verbDictionary.set("period", "periyot, dönem");
this.verbDictionary.set("shoot", "sut çekmek");
this.verbDictionary.set("administration", "yönetim, idare");
this.verbDictionary.set("zipper", "fermuar");
this.verbDictionary.set("good", "iyi");
this.verbDictionary.set("one", "bir");
this.verbDictionary.set("require", "gerekmek, gerektirmek");
this.verbDictionary.set("maybe", "belki, olabilir");
this.verbDictionary.set("authority", "yetki, otorite");
this.verbDictionary.set("hot", "sicak");
this.verbDictionary.set("today", "bugün");
this.verbDictionary.set("book", "kitap");
this.verbDictionary.set("must", "zorunlu");
this.verbDictionary.set("blue", "mavi");
this.verbDictionary.set("trip", "yolculuk");
this.verbDictionary.set("treat", "tedavi etmek");
this.verbDictionary.set("process", "süreç, islem");
this.verbDictionary.set("put", "koymak");
this.verbDictionary.set("until", "-a kadar");
this.verbDictionary.set("scientist", "bilim insani");
this.verbDictionary.set("both", "her ikisi de, ikisi de");
this.verbDictionary.set("stock", "stok");
this.verbDictionary.set("stuff", "sey, madde");
this.verbDictionary.set("itself", "kendisi");
this.verbDictionary.set("light", "isik");
this.verbDictionary.set("worry", "endise etmek");
this.verbDictionary.set("assume", "varsaymak, farzetmek");
this.verbDictionary.set("if", "eger");
this.verbDictionary.set("interesting", "ilginç");
this.verbDictionary.set("wear", "giyinmek");
this.verbDictionary.set("begin", "baslamak, baslatmak");
this.verbDictionary.set("fire", "ates");
this.verbDictionary.set("apple", "elma");
this.verbDictionary.set("heat", "sicaklik");
this.verbDictionary.set("personal", "kisisel");
this.verbDictionary.set("front", "ön");
this.verbDictionary.set("road", "karayolu, yol");
this.verbDictionary.set("apply", "uygulamak, basvurmak");
this.verbDictionary.set("health", "saglik");
this.verbDictionary.set("discuss", "tartismak");
this.verbDictionary.set("commercial", "ticari");
this.verbDictionary.set("patient", "hasta, sabirli, hosgörülü");
this.verbDictionary.set("save", "kayit etmek");
this.verbDictionary.set("attorney", "avukat, vekil");
this.verbDictionary.set("skill", "beceri");
this.verbDictionary.set("care", "bakim");
this.verbDictionary.set("new", "yeni");
this.verbDictionary.set("partner", "partner, ortak");
this.verbDictionary.set("information", "bilgi");
this.verbDictionary.set("green", "yesil");
this.verbDictionary.set("watch", "izlemek");
this.verbDictionary.set("legal", "yasal");
this.verbDictionary.set("again", "tekrar, yeniden");
this.verbDictionary.set("mean", "anlamina gelmek");
this.verbDictionary.set("down", "asagi");
this.verbDictionary.set("crime", "suç");
this.verbDictionary.set("attack", "saldiri, atak");
this.verbDictionary.set("staff", "personel");
this.verbDictionary.set("three", "üç");
this.verbDictionary.set("cup", "fincan");
this.verbDictionary.set("under", "altinda");
this.verbDictionary.set("court", "mahkeme");
this.verbDictionary.set("source", "kaynak");
this.verbDictionary.set("result", "sonuç");
this.verbDictionary.set("service", "hizmet");
this.verbDictionary.set("soldier", "asker");
this.verbDictionary.set("stage", "sahne");
this.verbDictionary.set("significant", "önemli");
this.verbDictionary.set("sell", "satmak");
this.verbDictionary.set("big", "büyük");
this.verbDictionary.set("final", "final, nihai");
this.verbDictionary.set("person", "kisi");
this.verbDictionary.set("cut", "kesmek");
this.verbDictionary.set("establish", "kurmak");
this.verbDictionary.set("program", "program");
this.verbDictionary.set("word", "kelime");
this.verbDictionary.set("series", "dizi, seri");
this.verbDictionary.set("medical", "tibbi");
this.verbDictionary.set("go", "gitmek");
this.verbDictionary.set("physical", "fiziksel");
this.verbDictionary.set("town", "kasaba");
this.verbDictionary.set("explain", "açiklamak");
this.verbDictionary.set("news", "haber");
this.verbDictionary.set("music", "müzik");
this.verbDictionary.set("follow", "takip etmek");
this.verbDictionary.set("here", "burada");
this.verbDictionary.set("mention", "deginmek, söz etmek");
this.verbDictionary.set("yelling", "seslenmek");
this.verbDictionary.set("difficult", "zor");
this.verbDictionary.set("rich", "zengin");
this.verbDictionary.set("standard", "standart");
this.verbDictionary.set("director", "yönetmen");
this.verbDictionary.set("general", "genel");
this.verbDictionary.set("deal", "anlasmak");
this.verbDictionary.set("none", "yok, hayir, hiçbiri, hiçbir sey");
this.verbDictionary.set("floor", "zemin");
this.verbDictionary.set("guy", "adam");
this.verbDictionary.set("two", "iki");
this.verbDictionary.set("very", "çok");
this.verbDictionary.set("heart", "kalp");
this.verbDictionary.set("between", "arasinda, aralarinda");
this.verbDictionary.set("certain", "belirli, kesin");
this.verbDictionary.set("it", "o (cansiz)");
this.verbDictionary.set("head", "kafa");
this.verbDictionary.set("others", "digerleri");
this.verbDictionary.set("room", "oda");
this.verbDictionary.set("join", "katilmak");
this.verbDictionary.set("experience", "deneyim");
this.verbDictionary.set("machine", "makine");
this.verbDictionary.set("much", "çok");
this.verbDictionary.set("right", "sag");
this.verbDictionary.set("region", "bölge");
this.verbDictionary.set("sound", "ses");
this.verbDictionary.set("oil", "yag");
this.verbDictionary.set("be", "olmak, var olmak");
this.verbDictionary.set("government", "hükümet");
this.verbDictionary.set("single", "tek");
this.verbDictionary.set("mind", "zihin");
this.verbDictionary.set("develop", "gelistirmek");
this.verbDictionary.set("performance", "performans");
this.verbDictionary.set("within", "içinde");
this.verbDictionary.set("participant", "katilimci");
this.verbDictionary.set("cancer", "kanser");
this.verbDictionary.set("career", "kariyer");
this.verbDictionary.set("occur", "meydana gelmek");
this.verbDictionary.set("manager", "müdür, yönetici");
this.verbDictionary.set("true", "dogru");
this.verbDictionary.set("son", "ogul");
this.verbDictionary.set("arrive", "varmak, ulasmak");
this.verbDictionary.set("interest", "faiz");
this.verbDictionary.set("end", "son");
this.verbDictionary.set("thing", "sey");
this.verbDictionary.set("former", "önceki, eski");
this.verbDictionary.set("hear", "duymak");
this.verbDictionary.set("forward", "ileri");
this.verbDictionary.set("sign", "isaret");
this.verbDictionary.set("professor", "profesör");
this.verbDictionary.set("by", "tarafindan, ile, göre, vasitasiyla");
this.verbDictionary.set("accept", "kabul etmek");
this.verbDictionary.set("adult", "yetiskin, eriskin");
this.verbDictionary.set("yesterday", "dün");
this.verbDictionary.set("degree", "derece");
this.verbDictionary.set("human", "insan");
this.verbDictionary.set("each", "her biri");
this.verbDictionary.set("sometimes", "ara sira");
this.verbDictionary.set("company", "sirket");
this.verbDictionary.set("do", "yapmak");
this.verbDictionary.set("decade", "on yil");
this.verbDictionary.set("boy", "erkek çocuk");
this.verbDictionary.set("yearly", "yillik");
this.verbDictionary.set("rise", "yükselmek");
this.verbDictionary.set("push", "itmek");
this.verbDictionary.set("play", "oynamak");
this.verbDictionary.set("always", "her zaman, daima");
this.verbDictionary.set("nation", "ulus");
this.verbDictionary.set("kill", "öldürmek");
this.verbDictionary.set("term", "terim");
this.verbDictionary.set("answer", "cevap, yanit");
this.verbDictionary.set("expert", "uzman");
this.verbDictionary.set("born", "dogmus, dogum");
this.verbDictionary.set("different", "farkli");
this.verbDictionary.set("message", "mesaj");
this.verbDictionary.set("political", "siyasi");
this.verbDictionary.set("or", "veya");
this.verbDictionary.set("religious", "dini");
this.verbDictionary.set("piece", "parça");
this.verbDictionary.set("family", "aile");
this.verbDictionary.set("too", "çok, fazla");
this.verbDictionary.set("especially", "özellikle");
this.verbDictionary.set("memory", "hafiza");
this.verbDictionary.set("quality", "kalite");
this.verbDictionary.set("enjoy", "keyif almak");
this.verbDictionary.set("yarn", "iplik");
this.verbDictionary.set("world", "dünya");
this.verbDictionary.set("fight", "kavga");
this.verbDictionary.set("eye", "göz");
this.verbDictionary.set("star", "yildiz");
this.verbDictionary.set("beyond", "ötesinde, öte");
this.verbDictionary.set("rate", "oran");
this.verbDictionary.set("meeting", "toplanti");
this.verbDictionary.set("ever", "hiç");
this.verbDictionary.set("research", "arastirma");
this.verbDictionary.set("attention", "dikkat");
this.verbDictionary.set("author", "yazar");
this.verbDictionary.set("clear", "temiz, açik");
this.verbDictionary.set("see", "görmek");
this.verbDictionary.set("zodiac", "burçlar kusagi");
this.verbDictionary.set("decision", "karar");
this.verbDictionary.set("teach", "ögretmek");
this.verbDictionary.set("although", "ragmen, karsin, gerçi");
this.verbDictionary.set("early", "erken");
this.verbDictionary.set("college", "kolej");
this.verbDictionary.set("me", "bana, beni");
this.verbDictionary.set("half", "yarim");
this.verbDictionary.set("people", "insanlar");
this.verbDictionary.set("trouble", "sorun");
this.verbDictionary.set("least", "en az");
this.verbDictionary.set("paper", "kagit");
this.verbDictionary.set("speak", "konusmak");
this.verbDictionary.set("style", "stil");
this.verbDictionary.set("law", "hukuk");
this.verbDictionary.set("everybody", "herkes");
this.verbDictionary.set("life", "hayat");
this.verbDictionary.set("manage", "yönetmek");
this.verbDictionary.set("respond", "yanitlamak");
this.verbDictionary.set("call", "aramak");
this.verbDictionary.set("get", "almak");
this.verbDictionary.set("brother", "erkek kardes");
this.verbDictionary.set("investment", "yatirim");
this.verbDictionary.set("minute", "dakika");
this.verbDictionary.set("agency", "ajans, acenta");
this.verbDictionary.set("southern", "güney, güneyli");
this.verbDictionary.set("give", "vermek");
this.verbDictionary.set("inside", "içeride");
this.verbDictionary.set("situation", "durum");
this.verbDictionary.set("score", "skor");
this.verbDictionary.set("relationship", "Iliski");
this.verbDictionary.set("great", "harika");
this.verbDictionary.set("able", "yapabilmek, yapabilen");
this.verbDictionary.set("with", "ile");
this.verbDictionary.set("smile", "gülümseme");
this.verbDictionary.set("reach", "ulasmak");
this.verbDictionary.set("reduce", "azaltmak, düsürmek");
this.verbDictionary.set("another", "digeri");
this.verbDictionary.set("institution", "kurum");
this.verbDictionary.set("spend", "harcamak");
this.verbDictionary.set("serious", "ciddi");
this.verbDictionary.set("make", "yapmak");
this.verbDictionary.set("likely", "muhtemel");
this.verbDictionary.set("into", "içine");
this.verbDictionary.set("stay", "kalmak");
this.verbDictionary.set("necessary", "gerekli");
this.verbDictionary.set("fast", "hizli");
this.verbDictionary.set("radio", "radyo");
this.verbDictionary.set("collection", "toplamak");
this.verbDictionary.set("effect", "efekt");
this.verbDictionary.set("where", "nerede");
this.verbDictionary.set("ask", "sormak, istemek");
this.verbDictionary.set("ability", "kabiliyet, yetenek, beceri");
this.verbDictionary.set("party", "parti");
this.verbDictionary.set("talk", "konusmak");
this.verbDictionary.set("in", "içinde");
this.verbDictionary.set("produce", "üretmek");
this.verbDictionary.set("exist", "var olmak");
this.verbDictionary.set("development", "gelisim, kalkinma");
this.verbDictionary.set("husband", "koca");
this.verbDictionary.set("heavy", "agir");
this.verbDictionary.set("zombie", "zombi");
this.verbDictionary.set("upon", "üzerinde");
this.verbDictionary.set("few", "az");
this.verbDictionary.set("number", "numara");
this.verbDictionary.set("church", "kilise");
this.verbDictionary.set("third", "üçüncü");
this.verbDictionary.set("senior", "kidemli, yasça büyük");
this.verbDictionary.set("operation", "ameliyat");
this.verbDictionary.set("country", "ülke");
this.verbDictionary.set("civil", "sivil");
this.verbDictionary.set("read", "okumak");
this.verbDictionary.set("simply", "basitçe");
this.verbDictionary.set("its", "onun (cansiz)");
this.verbDictionary.set("owner", "sahip");
this.verbDictionary.set("learn", "ögrenmek");
this.verbDictionary.set("control", "kontrol");
this.verbDictionary.set("often", "siklikla");
this.verbDictionary.set("tonight", "bu gece");
this.verbDictionary.set("whose", "kimin");
this.verbDictionary.set("have", "sahip olmak");
this.verbDictionary.set("movie", "film");
this.verbDictionary.set("bed", "yatak");
this.verbDictionary.set("lose", "kaybetmek");
this.verbDictionary.set("rock", "kaya");
this.verbDictionary.set("break", "kirmak");
this.verbDictionary.set("part", "bölüm");
this.verbDictionary.set("according", "göre");
this.verbDictionary.set("strategy", "strateji");
this.verbDictionary.set("economy", "ekonomi");
this.verbDictionary.set("alone", "yalniz, tek basina");
this.verbDictionary.set("tough", "sert");
this.verbDictionary.set("prove", "kanitlamak");
this.verbDictionary.set("south", "güney");
this.verbDictionary.set("police", "polis");
this.verbDictionary.set("idea", "fikir");
this.verbDictionary.set("kid", "çocuk");
this.verbDictionary.set("evidence", "delil");
this.verbDictionary.set("recently", "son günlerde");
this.verbDictionary.set("against", "karsi");
this.verbDictionary.set("want", "istemek");
this.verbDictionary.set("like", "sevmek, begenmek");
this.verbDictionary.set("laugh", "gülmek");
this.verbDictionary.set("else", "baska");
this.verbDictionary.set("morning", "sabah");
this.verbDictionary.set("training", "egitim, antrenman");
this.verbDictionary.set("lie", "yalan");
this.verbDictionary.set("draw", "çizmek");
this.verbDictionary.set("parent", "ebeveyn");
this.verbDictionary.set("huge", "kocaman");
this.verbDictionary.set("well", "daha iyi");
this.verbDictionary.set("total", "toplam, tüm");
this.verbDictionary.set("network", "ag");
this.verbDictionary.set("list", "liste");
this.verbDictionary.set("child", "çocuk");
this.verbDictionary.set("various", "çesitli");
this.verbDictionary.set("camera", "kamera");
this.verbDictionary.set("official", "resmi");
this.verbDictionary.set("clearly", "açikça");
this.verbDictionary.set("letter", "mektup");
this.verbDictionary.set("wish", "dilek, dilemek");
this.verbDictionary.set("zoology", "hayvan bilimi");
this.verbDictionary.set("real", "reel, gerçek");
this.verbDictionary.set("wife", "kadin es");
this.verbDictionary.set("particularly", "özellikle");
this.verbDictionary.set("ready", "hazir");
this.verbDictionary.set("past", "geçmis");
this.verbDictionary.set("yourself", "kendin");
this.verbDictionary.set("then", "sonra");
this.verbDictionary.set("art", "sanat");
this.verbDictionary.set("dark", "karanlik");
this.verbDictionary.set("nearly", "neredeyse");
this.verbDictionary.set("consumer", "tüketici");
this.verbDictionary.set("cultural", "kültürel");
this.verbDictionary.set("economic", "ekonomik");
this.verbDictionary.set("fact", "gerçek");
this.verbDictionary.set("buy", "satin almak");
this.verbDictionary.set("nature", "doga");
this.verbDictionary.set("policy", "politika");
this.verbDictionary.set("body", "vücut");
this.verbDictionary.set("sort", "çesit");
this.verbDictionary.set("reflect", "yansitmak");
this.verbDictionary.set("woman", "kadin");
this.verbDictionary.set("understand", "anlamak");
this.verbDictionary.set("difference", "fark");
this.verbDictionary.set("bank", "banka");
this.verbDictionary.set("lawyer", "avukat");
this.verbDictionary.set("activity", "faaliyet, etkinlik");
this.verbDictionary.set("study", "ders çalisma");
this.verbDictionary.set("couple", "çift");
this.verbDictionary.set("act", "eylem, davranis");
this.verbDictionary.set("short", "kisa");
this.verbDictionary.set("old", "yasli, eski");
this.verbDictionary.set("appear", "görünmek, gözükmek");
this.verbDictionary.set("impact", "etki");
this.verbDictionary.set("approach", "yaklasim, yaklasma");
this.verbDictionary.set("culture", "kültür");
this.verbDictionary.set("moment", "an");
this.verbDictionary.set("send", "göndermek");
this.verbDictionary.set("property", "gayrimenkul");
this.verbDictionary.set("energy", "enerji");
this.verbDictionary.set("would", "cekmisti");
this.verbDictionary.set("detail", "ayrinti");
this.verbDictionary.set("baby", "bebek");
this.verbDictionary.set("daughter", "kiz evlat");
this.verbDictionary.set("increase", "artirmak");
this.verbDictionary.set("affect", "etkilemek, etki etmek");
this.verbDictionary.set("fund", "fon, sermaye");
this.verbDictionary.set("plant", "bitki");
this.verbDictionary.set("house", "ev");
this.verbDictionary.set("customer", "müsteri");
this.verbDictionary.set("her", "ona (kadin)");
this.verbDictionary.set("center", "merkez");
this.verbDictionary.set("kind", "tür");
this.verbDictionary.set("improve", "iyilestirmek, iyi hale getirmek");
this.verbDictionary.set("certainly", "kesinlikle");
this.verbDictionary.set("shake", "sallamak");
this.verbDictionary.set("become", "olmak, haline gelmek");
this.verbDictionary.set("herself", "kendini");
this.verbDictionary.set("four", "dört");
this.verbDictionary.set("visit", "ziyaret etmek");
this.verbDictionary.set("white", "beyaz");
this.verbDictionary.set("model", "model");
this.verbDictionary.set("during", "sirasinda");
this.verbDictionary.set("only", "bir tek");
this.verbDictionary.set("write", "yazmak");
this.verbDictionary.set("east", "dogu");
this.verbDictionary.set("remove", "kaldirmak, uzaklastirmak, ortadan kaldirmak");
this.verbDictionary.set("peace", "baris");
this.verbDictionary.set("outside", "disinda");
this.verbDictionary.set("defense", "savunma");
this.verbDictionary.set("hour", "saat");
this.verbDictionary.set("perform", "yapmak, uygulamak, yerine getirmek");
this.verbDictionary.set("account", "hesap, açiklama");
this.verbDictionary.set("mother", "anne");
this.verbDictionary.set("any", "herhangi, hiç, her");
this.verbDictionary.set("sport", "spor");
this.verbDictionary.set("wide", "genis");
this.verbDictionary.set("effort", "çaba");
this.verbDictionary.set("late", "geç");
this.verbDictionary.set("toward", "-e dogru");
this.verbDictionary.set("girl", "kiz");
this.verbDictionary.set("item", "öge");
this.verbDictionary.set("large", "genis");
this.verbDictionary.set("blood", "kan");
this.verbDictionary.set("tax", "vergi");
this.verbDictionary.set("democratic", "demokratik");
this.verbDictionary.set("himself", "kendisi");
this.verbDictionary.set("management", "yönetim");
this.verbDictionary.set("notice", "fark etmek");
this.verbDictionary.set("soon", "yakinda");
this.verbDictionary.set("fish", "balik");
this.verbDictionary.set("pass", "geçmek");
this.verbDictionary.set("material", "malzeme");
this.verbDictionary.set("project", "proje");
this.verbDictionary.set("congress", "kongre");
this.verbDictionary.set("first", "ilk");
this.verbDictionary.set("test", "test");
this.verbDictionary.set("how", "nasil");
this.verbDictionary.set("other", "diger");
this.verbDictionary.set("drug", "uyusturucu");
this.verbDictionary.set("look", "bakmak");
this.verbDictionary.set("identify", "belirlemek, tanimak, tanimlamak");
this.verbDictionary.set("little", "küçük");
this.verbDictionary.set("doctor", "doktor");
this.verbDictionary.set("financial", "mali");
this.verbDictionary.set("purpose", "amaç");
this.verbDictionary.set("while", "iken");
this.verbDictionary.set("expect", "ummak");
this.verbDictionary.set("strong", "güçlü");
this.verbDictionary.set("charge", "sarj etmek");
this.verbDictionary.set("central", "merkezi");
this.verbDictionary.set("something", "bir sey");
this.verbDictionary.set("drop", "düsürmek");
this.verbDictionary.set("space", "bosluk");
this.verbDictionary.set("board", "yazi tahtasi");
this.verbDictionary.set("five", "bes");
this.verbDictionary.set("song", "sarki");
this.verbDictionary.set("forget", "unutmak");
this.verbDictionary.set("your", "senin");
this.verbDictionary.set("walk", "yürümek");
this.verbDictionary.set("night", "gece");
this.verbDictionary.set("last", "son");
this.verbDictionary.set("quite", "oldukça");
this.verbDictionary.set("foot", "ayak");
this.verbDictionary.set("leader", "lider");
this.verbDictionary.set("about", "hakkinda, ilgili, konusunda");
this.verbDictionary.set("my", "benim");
this.verbDictionary.set("school", "okul");
this.verbDictionary.set("threat", "tehdit");
this.verbDictionary.set("claim", "iddia etmek, iddia");
this.verbDictionary.set("these", "bunlar");
this.verbDictionary.set("better", "daha iyi, daha güzel, daha iyi sekilde");
this.verbDictionary.set("gun", "silah");
this.verbDictionary.set("check", "kontrol etmek, denetlemek");
this.verbDictionary.set("open", "açik");
this.verbDictionary.set("city", "sehir");
this.verbDictionary.set("still", "hala");
this.verbDictionary.set("film", "film");
this.verbDictionary.set("food", "gida, yiyecek");
this.verbDictionary.set("benefit", "yarar, fayda");
this.verbDictionary.set("quickly", "hizli bir sekilde");
this.verbDictionary.set("and", "ve, ile");
this.verbDictionary.set("design", "tasarim");
this.verbDictionary.set("usually", "genellikle");
this.verbDictionary.set("decide", "karar vermek");
this.verbDictionary.set("page", "sayfa");
this.verbDictionary.set("stand", "ayakta durmak, direnmek");
this.verbDictionary.set("chance", "sans");
this.verbDictionary.set("long", "uzun");
this.verbDictionary.set("time", "zaman");
this.verbDictionary.set("after", "sonra, ardindan, daha sonra");
this.verbDictionary.set("local", "yerel");
this.verbDictionary.set("death", "ölüm");
this.verbDictionary.set("imagine", "hayal etmek");
this.verbDictionary.set("pretty", "güzel");
this.verbDictionary.set("actually", "aslinda, gerçekte");
this.verbDictionary.set("sing", "sarki söylemek");
this.verbDictionary.set("afterwards", "ondan sonra");
this.verbDictionary.set("now", "simdi");
this.verbDictionary.set("million", "milyon");
this.verbDictionary.set("support", "destek");
this.verbDictionary.set("cell", "hücre");
this.verbDictionary.set("this", "bu");
this.verbDictionary.set("black", "siyah");
this.verbDictionary.set("drive", "sürmek");
this.verbDictionary.set("bill", "fatura");
this.verbDictionary.set("history", "tarih");
this.verbDictionary.set("computer", "bilgisayar");
this.verbDictionary.set("technology", "teknoloji");
this.verbDictionary.set("whom", "kime");
this.verbDictionary.set("sense", "algi, duyu");
this.verbDictionary.set("recognize", "tanimak");
this.verbDictionary.set("catch", "yakalamak");
this.verbDictionary.set("month", "ay");
this.verbDictionary.set("federal", "federal");
this.verbDictionary.set("take", "almak");
this.verbDictionary.set("that", "o");
this.verbDictionary.set("hold", "tutmak");
this.verbDictionary.set("possible", "mümkün");
this.verbDictionary.set("challenge", "meydan okuma");
this.verbDictionary.set("die", "ölmek");
this.verbDictionary.set("population", "nüfus");
this.verbDictionary.set("home", "ev");
this.verbDictionary.set("ten", "on");
this.verbDictionary.set("seat", "koltuk");
this.verbDictionary.set("instead", "yerine");
this.verbDictionary.set("statement", "beyan, ifade");
this.verbDictionary.set("station", "istasyon");
this.verbDictionary.set("create", "yaratmak");
this.verbDictionary.set("beat", "dövmek, yenmek");
this.verbDictionary.set("youth", "gençlik");
this.verbDictionary.set("natural", "dogal");
this.verbDictionary.set("describe", "tanimlamak");
this.verbDictionary.set("cold", "soguk");
this.verbDictionary.set("season", "sezon");
this.verbDictionary.set("zeppelin", "zepli");
this.verbDictionary.set("evening", "aksam");
this.verbDictionary.set("low", "düsük");
this.verbDictionary.set("lay", "yatirmak");
this.verbDictionary.set("response", "cevap vermek");
this.verbDictionary.set("war", "savas");
this.verbDictionary.set("run", "kosmak");
this.verbDictionary.set("step", "adim");
this.verbDictionary.set("fill", "doldurmak");
this.verbDictionary.set("point", "puan");
this.verbDictionary.set("pattern", "desen");
this.verbDictionary.set("scene", "sahne");
this.verbDictionary.set("reality", "gerçeklik");
this.verbDictionary.set("start", "baslama");
this.verbDictionary.set("feeling", "duygu");
this.verbDictionary.set("shoulder", "omuz");
this.verbDictionary.set("happy", "mutlu");
this.verbDictionary.set("up", "yukari");
this.verbDictionary.set("eight", "sekiz");
this.verbDictionary.set("including", "dahil olmak üzere");
this.verbDictionary.set("miss", "özlemek");
this.verbDictionary.set("system", "sistem");
this.verbDictionary.set("role", "rol");
this.verbDictionary.set("finally", "en sonunda");
this.verbDictionary.set("citizen", "vatandas");
this.verbDictionary.set("already", "zaten");
this.verbDictionary.set("door", "kapi");
this.verbDictionary.set("also", "ayrica, hem de");
this.verbDictionary.set("thank", "tesekkür etmek");
this.verbDictionary.set("social", "sosyal");
this.verbDictionary.set("firm", "firma");
this.verbDictionary.set("sister", "kiz kardes");
this.verbDictionary.set("positive", "pozitif");
this.verbDictionary.set("face", "yüz");
this.verbDictionary.set("foreign", "yabanci");
this.verbDictionary.set("subject", "konu");
this.verbDictionary.set("deep", "derin");
this.verbDictionary.set("democrat", "demokrat");
this.verbDictionary.set("main", "ana");
this.verbDictionary.set("site", "alan");
this.verbDictionary.set("reveal", "ortaya çikartmak, açiga vurmak");
this.verbDictionary.set("free", "ücretsiz");
this.verbDictionary.set("agreement", "anlasma, sözlesme");
this.verbDictionary.set("agent", "ajan");
this.verbDictionary.set("century", "yüzyil");
this.verbDictionary.set("anyone", "kimse, herhangi biri, hiç kimse");
this.verbDictionary.set("hope", "umut");
this.verbDictionary.set("individual", "bireysel");
this.verbDictionary.set("resource", "kaynak");
this.verbDictionary.set("include", "dahil etmek");
this.verbDictionary.set("billion", "milyar");
this.verbDictionary.set("cause", "sebep olmak");
this.verbDictionary.set("same", "ayni");
this.verbDictionary.set("week", "hafta");
this.verbDictionary.set("thousand", "bin");
this.verbDictionary.set("question", "soru");
this.verbDictionary.set("man", "adam, insan");
this.verbDictionary.set("water", "su");
this.verbDictionary.set("available", "müsait");
this.verbDictionary.set("field", "tarla, alan");
this.verbDictionary.set("small", "küçük");
this.verbDictionary.set("record", "kayit");
this.verbDictionary.set("force", "kuvvet");
this.verbDictionary.set("weapon", "silah");
this.verbDictionary.set("product", "ürün");
this.verbDictionary.set("trade", "ticaret");
this.verbDictionary.set("before", "önce");
this.verbDictionary.set("to", "mastar (mek, mak), karsi");
this.verbDictionary.set("television", "televizyon");
this.verbDictionary.set("they", "onlar");
this.verbDictionary.set("order", "siparis, siparis vermek");
this.verbDictionary.set("Mr", "bay");
this.verbDictionary.set("weight", "agirlik");
this.verbDictionary.set("amount", "miktar, tutar");
this.verbDictionary.set("carry", "tasimak");
this.verbDictionary.set("special", "özel");
this.verbDictionary.set("anywhere", "herhangi bir yere");
this.verbDictionary.set("every", "her");
this.verbDictionary.set("know", "bilmek");
this.verbDictionary.set("more", "daha");
this.verbDictionary.set("admit", "kabul etmek, itiraf etmek");
this.verbDictionary.set("picture", "resim");
this.verbDictionary.set("love", "ask");
this.verbDictionary.set("need", "ihtiyaç, gereksinim");
this.verbDictionary.set("security", "güvenlik");
this.verbDictionary.set("ago", "önce, evvel");
this.verbDictionary.set("near", "yakin");
this.verbDictionary.set("year", "yil");
this.verbDictionary.set("zebra", "zebra");
this.verbDictionary.set("race", "yaris");
this.verbDictionary.set("knowledge", "bilgi");
this.verbDictionary.set("since", "dan beri");
this.verbDictionary.set("popular", "popüler");
this.verbDictionary.set("report", "rapor");
this.verbDictionary.set("fail", "basarisiz");
this.verbDictionary.set("his", "onun (erkek)");
this.verbDictionary.set("production", "üretim");
this.verbDictionary.set("agree", "katilmak, hem fikir olmak");
this.verbDictionary.set("analysis", "analiz, çözümleme");
this.verbDictionary.set("fine", "iyi, güzel");
this.verbDictionary.set("everything", "her sey");
this.verbDictionary.set("remain", "kalmak, sürdürmek");
this.verbDictionary.set("science", "bilim");
this.verbDictionary.set("future", "gelecek");
this.verbDictionary.set("pain", "agri");
this.verbDictionary.set("election", "seçim");
this.verbDictionary.set("north", "kuzey");
this.verbDictionary.set("together", "birlikte");
this.verbDictionary.set("sure", "emin");
this.verbDictionary.set("involve", "içermek, kapsamak");
this.verbDictionary.set("happen", "olmak");
this.verbDictionary.set("officer", "memur");
this.verbDictionary.set("land", "arazi, toprak");
this.verbDictionary.set("live", "canli");
this.verbDictionary.set("so", "yani");
this.verbDictionary.set("though", "olsa da");
this.verbDictionary.set("media", "medya");
this.verbDictionary.set("practice", "uygulama, pratik");
this.verbDictionary.set("generation", "nesil");
this.verbDictionary.set("important", "önemli");
this.verbDictionary.set("may", "mayis ayi");
this.verbDictionary.set("pay", "ödemek");
this.verbDictionary.set("continue", "devam etmek");
this.verbDictionary.set("what", "ne");
this.verbDictionary.set("realize", "fark etmek");
this.verbDictionary.set("move", "hareket etmek");
this.verbDictionary.set("community", "topluluk");
this.verbDictionary.set("ball", "top");
this.verbDictionary.set("edge", "kenar, kiyi");
this.verbDictionary.set("add", "eklemek, ilave etmek");
this.verbDictionary.set("show", "göstermek");
this.verbDictionary.set("theory", "teori");
this.verbDictionary.set("okay", "tamam");
this.verbDictionary.set("just", "sadece");
this.verbDictionary.set("which", "hangi");
this.verbDictionary.set("try", "denemek");
this.verbDictionary.set("safe", "güvenli");
this.verbDictionary.set("job", "meslek");
this.verbDictionary.set("matter", "konu, mesele");
this.verbDictionary.set("market", "pazar");
this.verbDictionary.set("build", "insa etmek");
this.verbDictionary.set("a", "bir");
this.verbDictionary.set("wait", "beklemek");
this.verbDictionary.set("debate", "müzakere, tartisma");
this.verbDictionary.set("remember", "hatirlamak");
this.verbDictionary.set("member", "üye");
this.verbDictionary.set("thus", "böylece");
this.verbDictionary.set("coach", "koç");
this.verbDictionary.set("truth", "hakikat");
this.verbDictionary.set("direction", "yön");
this.verbDictionary.set("maintain", "sürdürmek");
this.verbDictionary.set("air", "hava");
this.verbDictionary.set("tell", "söylemek");
this.verbDictionary.set("who", "kim");
this.verbDictionary.set("nice", "iyi, güzel");
this.verbDictionary.set("size", "boyut");
this.verbDictionary.set("course", "ders");
this.verbDictionary.set("yet", "henüz");
this.verbDictionary.set("magazine", "dergi");
this.verbDictionary.set("compare", "karsilastirmak");
this.verbDictionary.set("raise", "yükseltmek");
this.verbDictionary.set("come", "gelmek");
this.verbDictionary.set("present", "mevcut");
this.verbDictionary.set("fall", "düsmek");
this.verbDictionary.set("seek", "aramak");
this.verbDictionary.set("republican", "cumhuriyetçi");
this.verbDictionary.set("return", "dönüs");
this.verbDictionary.set("afternoon", "ögleden sonra");
this.verbDictionary.set("building", "bina");
this.verbDictionary.set("yes", "evet");
this.verbDictionary.set("day", "gün");
this.verbDictionary.set("prevent", "engel olmak");
this.verbDictionary.set("eat", "yemek yemek");
this.verbDictionary.set("class", "sinif");
this.verbDictionary.set("seven", "yedi");
this.verbDictionary.set("use", "kullanmak");
this.verbDictionary.set("pull", "çekmek");
this.verbDictionary.set("specific", "özel");
this.verbDictionary.set("choice", "seçim, seçenek");
this.verbDictionary.set("office", "ofis");
this.verbDictionary.set("enough", "yeterli");
this.verbDictionary.set("growth", "büyüme");
this.verbDictionary.set("writer", "yazar");
this.verbDictionary.set("nothing", "hiçbir sey");
this.verbDictionary.set("say", "söylemek");
this.verbDictionary.set("street", "sokak");
this.verbDictionary.set("enter", "girmek, katilmak");
this.verbDictionary.set("window", "pencere");
this.verbDictionary.set("image", "görüntü, resim");
this.verbDictionary.set("there", "orada");
this.verbDictionary.set("teacher", "ögretmen");
this.verbDictionary.set("organization", "organizasyon");
this.verbDictionary.set("leg", "bacak");
this.verbDictionary.set("red", "kirmizi");
this.verbDictionary.set("less", "az");
this.verbDictionary.set("never", "asla");
this.verbDictionary.set("budget", "bütçe");
this.verbDictionary.set("western", "batida");
this.verbDictionary.set("hundred", "yüz");
this.verbDictionary.set("leave", "ayrilmak");
this.verbDictionary.set("their", "onlarin");
this.verbDictionary.set("position", "pozisyon");
this.verbDictionary.set("six", "alti");
this.verbDictionary.set("suffer", "aci çekmek");
this.verbDictionary.set("hotel", "otel");
this.verbDictionary.set("avoid", "önlemek, kaçinmak");
this.verbDictionary.set("behind", "arkasinda, gerisinde");
this.verbDictionary.set("nor", "ne de");
this.verbDictionary.set("skin", "cilt");
this.verbDictionary.set("meet", "bulusmak");
this.verbDictionary.set("line", "çizgi, sira");
this.verbDictionary.set("level", "seviye");
this.verbDictionary.set("simple", "basit");
this.verbDictionary.set("color", "renk");
this.verbDictionary.set("own", "kendi");
this.verbDictionary.set("someone", "birisi");
this.verbDictionary.set("mission", "misyon");
this.verbDictionary.set("base", "üs, temel, baz");
this.verbDictionary.set("full", "tam");
this.verbDictionary.set("high", "yüksek");
this.verbDictionary.set("international", "uluslararasi");
this.verbDictionary.set("allow", "izin vermek");
this.verbDictionary.set("perhaps", "belki");
this.verbDictionary.set("change", "degisiklik");
this.verbDictionary.set("ahead", "önde, ileri");
this.verbDictionary.set("kitchen", "mutfak");
this.verbDictionary.set("tend", "yönelmek, egilmek");
this.verbDictionary.set("state", "devlet, durum");
this.verbDictionary.set("measure", "ölçmek");
this.verbDictionary.set("vote", "oy");
this.verbDictionary.set("set", "ayarlamak");
this.verbDictionary.set("should", "meli, mali");
this.verbDictionary.set("form", "form");
this.verbDictionary.set("bar", "bar");
this.verbDictionary.set("glass", "bardak");
this.verbDictionary.set("throughout", "boyunca");
this.verbDictionary.set("choose", "seçmek");
this.verbDictionary.set("along", "boyunca, yani sira");
this.verbDictionary.set("worker", "isçi");
this.verbDictionary.set("public", "halka açik");
this.verbDictionary.set("despite", "ragmen, aksine");
this.verbDictionary.set("place", "yer, mekan");
this.verbDictionary.set("friend", "arkadas");
this.verbDictionary.set("case", "dava");
this.verbDictionary.set("april", "nisan");
this.verbDictionary.set("language", "dil");
this.verbDictionary.set("behavior", "davranis, tutum, hareket");
this.verbDictionary.set("several", "birkaç");
this.verbDictionary.set("later", "sonra");
this.verbDictionary.set("national", "ulusal");
this.verbDictionary.set("opportunity", "firsat");
this.verbDictionary.set("successful", "basarili");
this.verbDictionary.set("artist", "sanatçi");
this.verbDictionary.set("candidate", "aday");
this.verbDictionary.set("best", "en iyi, en iyisi, en");
this.verbDictionary.set("keep", "tutmak");
this.verbDictionary.set("lot", "çok");
this.verbDictionary.set("event", "olay");
this.verbDictionary.set("let", "izin vermek");
this.verbDictionary.set("out", "disari");
this.verbDictionary.set("whatever", "her neyse");
this.verbDictionary.set("fear", "korku");
this.verbDictionary.set("area", "alan, bölge");
this.verbDictionary.set("story", "öykü");
this.verbDictionary.set("left", "ayrildi");
this.verbDictionary.set("problem", "problem, sorun");
this.verbDictionary.set("middle", "orta");
this.verbDictionary.set("feel", "hissetmek");
this.verbDictionary.set("focus", "odaklanmak");
this.verbDictionary.set("dog", "köpek");
this.verbDictionary.set("newspaper", "gazete");
this.verbDictionary.set("employee", "çalisan");
this.verbDictionary.set("hospital", "hastane");
this.verbDictionary.set("surface", "yüzey");
this.verbDictionary.set("power", "güç");
this.verbDictionary.set("industry", "endüstri");
this.verbDictionary.set("fly", "uçmak");
this.verbDictionary.set("zoom", "yakinlasmak, zoom yapmak");
this.verbDictionary.set("method", "yöntem");
this.verbDictionary.set("hair", "saç");
this.verbDictionary.set("Mrs", "bayan");
this.verbDictionary.set("shot", "atis");
this.verbDictionary.set("finger", "parmak");
this.verbDictionary.set("action", "eylem, etki, hareket");
this.verbDictionary.set("sit", "oturmak");
this.verbDictionary.set("stop", "dur, durmak");
this.verbDictionary.set("receive", "teslim almak");
this.verbDictionary.set("painting", "boyama");
this.verbDictionary.set("education", "egitim");
this.verbDictionary.set("everyone", "herkes, her biri");
this.verbDictionary.set("beautiful", "güzel");
this.verbDictionary.set("gas", "gaz");
this.verbDictionary.set("similar", "benzer");
this.verbDictionary.set("trial", "deneme, test");
this.verbDictionary.set("recent", "son");
this.verbDictionary.set("father", "baba");
this.verbDictionary.set("box", "kutu");
this.verbDictionary.set("those", "bunlar");
this.verbDictionary.set("note", "not");
this.verbDictionary.set("find", "bulmak");
this.verbDictionary.set("military", "askeri");
this.verbDictionary.set("win", "kazanmak");
this.verbDictionary.set("concern", "iliskisi olmak, ait olmak, ilgilendirmek");
this.verbDictionary.set("factor", "faktör");
this.verbDictionary.set("grow", "büyümek");
this.verbDictionary.set("team", "takim");
this.verbDictionary.set("bad", "kötü");
this.verbDictionary.set("hand", "el");
this.verbDictionary.set("structure", "yapi");
this.verbDictionary.set("range", "menzil, aralik");
this.verbDictionary.set("campaign", "kampanya");
this.verbDictionary.set("serve", "servis");
this.verbDictionary.set("finish", "bitis");
this.verbDictionary.set("garden", "bahçe");
this.verbDictionary.set("private", "özel");
this.verbDictionary.set("not", "degil");
this.verbDictionary.set("cost", "maliyet");
this.verbDictionary.set("section", "bölüm, kesit");
this.verbDictionary.set("violence", "siddet");
this.verbDictionary.set("onto", "üstüne");
this.verbDictionary.set("she", "o (kadin)");
this.verbDictionary.set("many", "çok");
this.verbDictionary.set("guess", "tahmin");
this.verbDictionary.set("believe", "inanmak");
this.verbDictionary.set("dinner", "aksam yemegi");
this.verbDictionary.set("turn", "çevirmek");
this.verbDictionary.set("entire", "tamami");
this.verbDictionary.set("all right", "peki");
this.verbDictionary.set("somebody", "birileri");
this.verbDictionary.set("car", "araba");
this.verbDictionary.set("we", "biz");
this.verbDictionary.set("player", "oyuncu");
this.verbDictionary.set("suggest", "önermek");
this.verbDictionary.set("president", "devlet baskani");
this.verbDictionary.set("pressure", "basinç");
this.verbDictionary.set("back", "geri");
this.verbDictionary.set("yard", "avlu");
this.verbDictionary.set("side", "yan");
this.verbDictionary.set("way", "yol, yön, yöntem");
this.verbDictionary.set("hit", "çarpmak");
this.verbDictionary.set("without", "olmadan");
this.verbDictionary.set("key", "anahtar");
this.verbDictionary.set("responsibility", "sorumluluk");
this.verbDictionary.set("throw", "atmak");
this.verbDictionary.set("represent", "temsil etmek");
this.verbDictionary.set("rather", "daha dogrusu");
this.verbDictionary.set("share", "paylasmak");
this.verbDictionary.set("executive", "yönetici");
this.verbDictionary.set("themselves", "kendilerini");
this.verbDictionary.set("reason", "neden");
this.verbDictionary.set("tree", "agaç");
this.verbDictionary.set("mouth", "agiz");
this.verbDictionary.set("you", "sen");




}

   get2(){
    this.inputEnFocus();
    this.userInputEn="";
    this.isTranslationCorrect2=false;
    // Rastgele bir kelime seçme
let keys2 = Array.from(this.verbDictionary2.keys());
 this.randomKey2 = keys2[Math.floor(Math.random() * 5)];

// Seçilen kelimenin Türkçe karşılığını alma
this.turkishEquivalent2 = this.verbDictionary2.get(this.randomKey2);

// Sonucu ekrana basma
console.log("İngilizce:", this.randomKey2);
console.log("Türkçe:", this.turkishEquivalent2);




  }

  showWord2(){
    this.userInputEn=this.randomKey2;
    this.isTranslationCorrect2=true;
    this.inputEnFocus();

  }
  hint2(){
    this.userInputEn=this.randomKey2.substring(0,2);
    this.inputEnFocus();
  }

  del2(){
 
    this.verbDictionary2.delete(this.randomKey2);
    console.log("Silindi:", this.randomKey2);
   
    this.get2();
    this.inputEnFocus();

  }
 

   load2(){
    this.verbDictionary.set("easy", "kolay");
this.verbDictionary.set("society", "toplum");
this.verbDictionary.set("option", "seçenek");
this.verbDictionary.set("offer", "teklif etmek");
this.verbDictionary.set("age", "yas");
this.verbDictionary.set("figure", "sekil");
this.verbDictionary.set("west", "bati");
this.verbDictionary.set("either", "ya");
this.verbDictionary.set("voice", "ses");
this.verbDictionary.set("among", "arasinda, içinde");
this.verbDictionary.set("across", "karsisinda");
this.verbDictionary.set("listen", "dinlemek");
this.verbDictionary.set("example", "örnek");
this.verbDictionary.set("majority", "çogunluk");
this.verbDictionary.set("victim", "kurban");
this.verbDictionary.set("interview", "röportaj");
this.verbDictionary.set("phone", "telefon");
this.verbDictionary.set("exactly", "kesinlikle");
this.verbDictionary.set("chair", "sandalye");
this.verbDictionary.set("value", "deger");
this.verbDictionary.set("when", "ne zaman");
this.verbDictionary.set("per", "basina, göre");
this.verbDictionary.set("issue", "sorun");
this.verbDictionary.set("zoo", "hayvanat bahçesi");
this.verbDictionary.set("sea", "deniz");
this.verbDictionary.set("provide", "saglamak");
this.verbDictionary.set("task", "görev");
this.verbDictionary.set("spring", "bahar");
this.verbDictionary.set("lead", "öncülük etmek");
this.verbDictionary.set("contain", "içermek");
this.verbDictionary.set("relate", "Iliski kurmak");
this.verbDictionary.set("anything", "bir seyi herhangi bir sey, hiçbir sey");
this.verbDictionary.set("unit", "ünite");
this.verbDictionary.set("protect", "korumak");
this.verbDictionary.set("american", "amerikan");
this.verbDictionary.set("over", "bitti");
this.verbDictionary.set("address", "adres");
this.verbDictionary.set("myself", "kendim");
this.verbDictionary.set("success", "basari");
this.verbDictionary.set("loss", "kayip");
this.verbDictionary.set("particular", "özel, belirli");
this.verbDictionary.set("anyway", "her halükârda");
this.verbDictionary.set("treatment", "tedavi");
this.verbDictionary.set("cover", "örtmek");
this.verbDictionary.set("him", "onu (erkek)");
this.verbDictionary.set("rest", "dinlenme");
this.verbDictionary.set("but", "fakat, ama, lakin");
this.verbDictionary.set("rule", "kural");
this.verbDictionary.set("through", "vasitasiyla");
this.verbDictionary.set("price", "fiyat");
this.verbDictionary.set("view", "görünüm");
this.verbDictionary.set("he", "o (erkek)");
this.verbDictionary.set("pick", "almak");
this.verbDictionary.set("off", "kapali");
this.verbDictionary.set("wind", "rüzgar");
this.verbDictionary.set("marriage", "evlilik");
this.verbDictionary.set("character", "karakter");
this.verbDictionary.set("risk", "risk");
this.verbDictionary.set("almost", "neredeyse, hemen hemen");
this.verbDictionary.set("for", "için");
this.verbDictionary.set("discussion", "tartisma");
this.verbDictionary.set("however", "ancak");
this.verbDictionary.set("politics", "siyaset");
this.verbDictionary.set("close", "kapatmak");
this.verbDictionary.set("type", "tip, tür, model");
this.verbDictionary.set("audience", "seyirci, izleyici");
this.verbDictionary.set("our", "bizim");
this.verbDictionary.set("goal", "hedef");
this.verbDictionary.set("determine", "belirlemek");
this.verbDictionary.set("can", "yapabilmek");
this.verbDictionary.set("game", "oyun");
this.verbDictionary.set("probably", "muhtemelen");
this.verbDictionary.set("traditional", "geleneksel");
this.verbDictionary.set("hang", "asmak");
this.verbDictionary.set("consider", "dikkate almak");
this.verbDictionary.set("such", "böyle");
this.verbDictionary.set("some", "bazi");
this.verbDictionary.set("bag", "sirt çantasi");
this.verbDictionary.set("common", "ortak");
this.verbDictionary.set("young", "genç");
this.verbDictionary.set("why", "niçin?");
this.verbDictionary.set("disease", "hastalik");
this.verbDictionary.set("hard", "zor");
this.verbDictionary.set("group", "grup");
this.verbDictionary.set("most", "çogu");
this.verbDictionary.set("discover", "kesfetmek");
this.verbDictionary.set("plan", "plan");
this.verbDictionary.set("as", "gibi, olarak");
this.verbDictionary.set("travel", "seyahat");
this.verbDictionary.set("suddenly", "aniden");
this.verbDictionary.set("really", "gerçekten");
this.verbDictionary.set("seem", "görünmek");
this.verbDictionary.set("name", "isim");
this.verbDictionary.set("data", "veri");
this.verbDictionary.set("top", "üst");
this.verbDictionary.set("ground", "zemin");
this.verbDictionary.set("table", "masa, tablo");
this.verbDictionary.set("work", "çalismak");
this.verbDictionary.set("dream", "rüya");
this.verbDictionary.set("prepare", "hazirlamak");
this.verbDictionary.set("condition", "sart");
this.verbDictionary.set("might", "belki");
this.verbDictionary.set("card", "kart");
this.verbDictionary.set("above", "yukarida");
this.verbDictionary.set("thought", "düsündü");
this.verbDictionary.set("wonder", "merak etmek, sasmak");
this.verbDictionary.set("modern", "modern");
this.verbDictionary.set("all", "her sey, tüm, bütün");
this.verbDictionary.set("student", "ögrenci");
this.verbDictionary.set("capital", "baskent");
this.verbDictionary.set("second", "ikinci");
this.verbDictionary.set("poor", "fakir");
this.verbDictionary.set("on", "üzerinde");
this.verbDictionary.set("conference", "konferans");
this.verbDictionary.set("because", "çünkü");
this.verbDictionary.set("away", "uzak, uzakta");
this.verbDictionary.set("summer", "yaz");
this.verbDictionary.set("speech", "konusma");
this.verbDictionary.set("environment", "çevre");
this.verbDictionary.set("dead", "ölü");
this.verbDictionary.set("store", "magaza");
this.verbDictionary.set("bring", "getirmek");
this.verbDictionary.set("no", "hayir");
this.verbDictionary.set("money", "para");
this.verbDictionary.set("them", "onlari");
this.verbDictionary.set("think", "düsünmek");
this.verbDictionary.set("help", "yardim");
this.verbDictionary.set("once", "bir zamanlar");
this.verbDictionary.set("next", "sonraki");
this.verbDictionary.set("current", "su andaki");
this.verbDictionary.set("wall", "duvar");
this.verbDictionary.set("environmental", "çevreci");
this.verbDictionary.set("us", "bize");
this.verbDictionary.set("wrong", "yanlis");
this.verbDictionary.set("animal", "hayvan");
this.verbDictionary.set("indicate", "belirtmek");
this.verbDictionary.set("movement", "hareket");
this.verbDictionary.set("professional", "profesyonel");
this.verbDictionary.set("article", "makale, yazi");
this.verbDictionary.set("indeed", "aslinda");
this.verbDictionary.set("far", "uzak");
this.verbDictionary.set("business", "is");
this.verbDictionary.set("period", "periyot, dönem");
this.verbDictionary.set("shoot", "sut çekmek");
this.verbDictionary.set("administration", "yönetim, idare");
this.verbDictionary.set("zipper", "fermuar");
this.verbDictionary.set("good", "iyi");
this.verbDictionary.set("one", "bir");
this.verbDictionary.set("require", "gerekmek, gerektirmek");
this.verbDictionary.set("maybe", "belki, olabilir");
this.verbDictionary.set("authority", "yetki, otorite");
this.verbDictionary.set("hot", "sicak");
this.verbDictionary.set("today", "bugün");
this.verbDictionary.set("book", "kitap");
this.verbDictionary.set("must", "zorunlu");
this.verbDictionary.set("blue", "mavi");
this.verbDictionary.set("trip", "yolculuk");
this.verbDictionary.set("treat", "tedavi etmek");
this.verbDictionary.set("process", "süreç, islem");
this.verbDictionary.set("put", "koymak");
this.verbDictionary.set("until", "-a kadar");
this.verbDictionary.set("scientist", "bilim insani");
this.verbDictionary.set("both", "her ikisi de, ikisi de");
this.verbDictionary.set("stock", "stok");
this.verbDictionary.set("stuff", "sey, madde");
this.verbDictionary.set("itself", "kendisi");
this.verbDictionary.set("light", "isik");
this.verbDictionary.set("worry", "endise etmek");
this.verbDictionary.set("assume", "varsaymak, farzetmek");
this.verbDictionary.set("if", "eger");
this.verbDictionary.set("interesting", "ilginç");
this.verbDictionary.set("wear", "giyinmek");
this.verbDictionary.set("begin", "baslamak, baslatmak");
this.verbDictionary.set("fire", "ates");
this.verbDictionary.set("apple", "elma");
this.verbDictionary.set("heat", "sicaklik");
this.verbDictionary.set("personal", "kisisel");
this.verbDictionary.set("front", "ön");
this.verbDictionary.set("road", "karayolu, yol");
this.verbDictionary.set("apply", "uygulamak, basvurmak");
this.verbDictionary.set("health", "saglik");
this.verbDictionary.set("discuss", "tartismak");
this.verbDictionary.set("commercial", "ticari");
this.verbDictionary.set("patient", "hasta, sabirli, hosgörülü");
this.verbDictionary.set("save", "kayit etmek");
this.verbDictionary.set("attorney", "avukat, vekil");
this.verbDictionary.set("skill", "beceri");
this.verbDictionary.set("care", "bakim");
this.verbDictionary.set("new", "yeni");
this.verbDictionary.set("partner", "partner, ortak");
this.verbDictionary.set("information", "bilgi");
this.verbDictionary.set("green", "yesil");
this.verbDictionary.set("watch", "izlemek");
this.verbDictionary.set("legal", "yasal");
this.verbDictionary.set("again", "tekrar, yeniden");
this.verbDictionary.set("mean", "anlamina gelmek");
this.verbDictionary.set("down", "asagi");
this.verbDictionary.set("crime", "suç");
this.verbDictionary.set("attack", "saldiri, atak");
this.verbDictionary.set("staff", "personel");
this.verbDictionary.set("three", "üç");
this.verbDictionary.set("cup", "fincan");
this.verbDictionary.set("under", "altinda");
this.verbDictionary.set("court", "mahkeme");
this.verbDictionary.set("source", "kaynak");
this.verbDictionary.set("result", "sonuç");
this.verbDictionary.set("service", "hizmet");
this.verbDictionary.set("soldier", "asker");
this.verbDictionary.set("stage", "sahne");
this.verbDictionary.set("significant", "önemli");
this.verbDictionary.set("sell", "satmak");
this.verbDictionary.set("big", "büyük");
this.verbDictionary.set("final", "final, nihai");
this.verbDictionary.set("person", "kisi");
this.verbDictionary.set("cut", "kesmek");
this.verbDictionary.set("establish", "kurmak");
this.verbDictionary.set("program", "program");
this.verbDictionary.set("word", "kelime");
this.verbDictionary.set("series", "dizi, seri");
this.verbDictionary.set("medical", "tibbi");
this.verbDictionary.set("go", "gitmek");
this.verbDictionary.set("physical", "fiziksel");
this.verbDictionary.set("town", "kasaba");
this.verbDictionary.set("explain", "açiklamak");
this.verbDictionary.set("news", "haber");
this.verbDictionary.set("music", "müzik");
this.verbDictionary.set("follow", "takip etmek");
this.verbDictionary.set("here", "burada");
this.verbDictionary.set("mention", "deginmek, söz etmek");
this.verbDictionary.set("yelling", "seslenmek");
this.verbDictionary.set("difficult", "zor");
this.verbDictionary.set("rich", "zengin");
this.verbDictionary.set("standard", "standart");
this.verbDictionary.set("director", "yönetmen");
this.verbDictionary.set("general", "genel");
this.verbDictionary.set("deal", "anlasmak");
this.verbDictionary.set("none", "yok, hayir, hiçbiri, hiçbir sey");
this.verbDictionary.set("floor", "zemin");
this.verbDictionary.set("guy", "adam");
this.verbDictionary.set("two", "iki");
this.verbDictionary.set("very", "çok");
this.verbDictionary.set("heart", "kalp");
this.verbDictionary.set("between", "arasinda, aralarinda");
this.verbDictionary.set("certain", "belirli, kesin");
this.verbDictionary.set("it", "o (cansiz)");
this.verbDictionary.set("head", "kafa");
this.verbDictionary.set("others", "digerleri");
this.verbDictionary.set("room", "oda");
this.verbDictionary.set("join", "katilmak");
this.verbDictionary.set("experience", "deneyim");
this.verbDictionary.set("machine", "makine");
this.verbDictionary.set("much", "çok");
this.verbDictionary.set("right", "sag");
this.verbDictionary.set("region", "bölge");
this.verbDictionary.set("sound", "ses");
this.verbDictionary.set("oil", "yag");
this.verbDictionary.set("be", "olmak, var olmak");
this.verbDictionary.set("government", "hükümet");
this.verbDictionary.set("single", "tek");
this.verbDictionary.set("mind", "zihin");
this.verbDictionary.set("develop", "gelistirmek");
this.verbDictionary.set("performance", "performans");
this.verbDictionary.set("within", "içinde");
this.verbDictionary.set("participant", "katilimci");
this.verbDictionary.set("cancer", "kanser");
this.verbDictionary.set("career", "kariyer");
this.verbDictionary.set("occur", "meydana gelmek");
this.verbDictionary.set("manager", "müdür, yönetici");
this.verbDictionary.set("true", "dogru");
this.verbDictionary.set("son", "ogul");
this.verbDictionary.set("arrive", "varmak, ulasmak");
this.verbDictionary.set("interest", "faiz");
this.verbDictionary.set("end", "son");
this.verbDictionary.set("thing", "sey");
this.verbDictionary.set("former", "önceki, eski");
this.verbDictionary.set("hear", "duymak");
this.verbDictionary.set("forward", "ileri");
this.verbDictionary.set("sign", "isaret");
this.verbDictionary.set("professor", "profesör");
this.verbDictionary.set("by", "tarafindan, ile, göre, vasitasiyla");
this.verbDictionary.set("accept", "kabul etmek");
this.verbDictionary.set("adult", "yetiskin, eriskin");
this.verbDictionary.set("yesterday", "dün");
this.verbDictionary.set("degree", "derece");
this.verbDictionary.set("human", "insan");
this.verbDictionary.set("each", "her biri");
this.verbDictionary.set("sometimes", "ara sira");
this.verbDictionary.set("company", "sirket");
this.verbDictionary.set("do", "yapmak");
this.verbDictionary.set("decade", "on yil");
this.verbDictionary.set("boy", "erkek çocuk");
this.verbDictionary.set("yearly", "yillik");
this.verbDictionary.set("rise", "yükselmek");
this.verbDictionary.set("push", "itmek");
this.verbDictionary.set("play", "oynamak");
this.verbDictionary.set("always", "her zaman, daima");
this.verbDictionary.set("nation", "ulus");
this.verbDictionary.set("kill", "öldürmek");
this.verbDictionary.set("term", "terim");
this.verbDictionary.set("answer", "cevap, yanit");
this.verbDictionary.set("expert", "uzman");
this.verbDictionary.set("born", "dogmus, dogum");
this.verbDictionary.set("different", "farkli");
this.verbDictionary.set("message", "mesaj");
this.verbDictionary.set("political", "siyasi");
this.verbDictionary.set("or", "veya");
this.verbDictionary.set("religious", "dini");
this.verbDictionary.set("piece", "parça");
this.verbDictionary.set("family", "aile");
this.verbDictionary.set("too", "çok, fazla");
this.verbDictionary.set("especially", "özellikle");
this.verbDictionary.set("memory", "hafiza");
this.verbDictionary.set("quality", "kalite");
this.verbDictionary.set("enjoy", "keyif almak");
this.verbDictionary.set("yarn", "iplik");
this.verbDictionary.set("world", "dünya");
this.verbDictionary.set("fight", "kavga");
this.verbDictionary.set("eye", "göz");
this.verbDictionary.set("star", "yildiz");
this.verbDictionary.set("beyond", "ötesinde, öte");
this.verbDictionary.set("rate", "oran");
this.verbDictionary.set("meeting", "toplanti");
this.verbDictionary.set("ever", "hiç");
this.verbDictionary.set("research", "arastirma");
this.verbDictionary.set("attention", "dikkat");
this.verbDictionary.set("author", "yazar");
this.verbDictionary.set("clear", "temiz, açik");
this.verbDictionary.set("see", "görmek");
this.verbDictionary.set("zodiac", "burçlar kusagi");
this.verbDictionary.set("decision", "karar");
this.verbDictionary.set("teach", "ögretmek");
this.verbDictionary.set("although", "ragmen, karsin, gerçi");
this.verbDictionary.set("early", "erken");
this.verbDictionary.set("college", "kolej");
this.verbDictionary.set("me", "bana, beni");
this.verbDictionary.set("half", "yarim");
this.verbDictionary.set("people", "insanlar");
this.verbDictionary.set("trouble", "sorun");
this.verbDictionary.set("least", "en az");
this.verbDictionary.set("paper", "kagit");
this.verbDictionary.set("speak", "konusmak");
this.verbDictionary.set("style", "stil");
this.verbDictionary.set("law", "hukuk");
this.verbDictionary.set("everybody", "herkes");
this.verbDictionary.set("life", "hayat");
this.verbDictionary.set("manage", "yönetmek");
this.verbDictionary.set("respond", "yanitlamak");
this.verbDictionary.set("call", "aramak");
this.verbDictionary.set("get", "almak");
this.verbDictionary.set("brother", "erkek kardes");
this.verbDictionary.set("investment", "yatirim");
this.verbDictionary.set("minute", "dakika");
this.verbDictionary.set("agency", "ajans, acenta");
this.verbDictionary.set("southern", "güney, güneyli");
this.verbDictionary.set("give", "vermek");
this.verbDictionary.set("inside", "içeride");
this.verbDictionary.set("situation", "durum");
this.verbDictionary.set("score", "skor");
this.verbDictionary.set("relationship", "Iliski");
this.verbDictionary.set("great", "harika");
this.verbDictionary.set("able", "yapabilmek, yapabilen");
this.verbDictionary.set("with", "ile");
this.verbDictionary.set("smile", "gülümseme");
this.verbDictionary.set("reach", "ulasmak");
this.verbDictionary.set("reduce", "azaltmak, düsürmek");
this.verbDictionary.set("another", "digeri");
this.verbDictionary.set("institution", "kurum");
this.verbDictionary.set("spend", "harcamak");
this.verbDictionary.set("serious", "ciddi");
this.verbDictionary.set("make", "yapmak");
this.verbDictionary.set("likely", "muhtemel");
this.verbDictionary.set("into", "içine");
this.verbDictionary.set("stay", "kalmak");
this.verbDictionary.set("necessary", "gerekli");
this.verbDictionary.set("fast", "hizli");
this.verbDictionary.set("radio", "radyo");
this.verbDictionary.set("collection", "toplamak");
this.verbDictionary.set("effect", "efekt");
this.verbDictionary.set("where", "nerede");
this.verbDictionary.set("ask", "sormak, istemek");
this.verbDictionary.set("ability", "kabiliyet, yetenek, beceri");
this.verbDictionary.set("party", "parti");
this.verbDictionary.set("talk", "konusmak");
this.verbDictionary.set("in", "içinde");
this.verbDictionary.set("produce", "üretmek");
this.verbDictionary.set("exist", "var olmak");
this.verbDictionary.set("development", "gelisim, kalkinma");
this.verbDictionary.set("husband", "koca");
this.verbDictionary.set("heavy", "agir");
this.verbDictionary.set("zombie", "zombi");
this.verbDictionary.set("upon", "üzerinde");
this.verbDictionary.set("few", "az");
this.verbDictionary.set("number", "numara");
this.verbDictionary.set("church", "kilise");
this.verbDictionary.set("third", "üçüncü");
this.verbDictionary.set("senior", "kidemli, yasça büyük");
this.verbDictionary.set("operation", "ameliyat");
this.verbDictionary.set("country", "ülke");
this.verbDictionary.set("civil", "sivil");
this.verbDictionary.set("read", "okumak");
this.verbDictionary.set("simply", "basitçe");
this.verbDictionary.set("its", "onun (cansiz)");
this.verbDictionary.set("owner", "sahip");
this.verbDictionary.set("learn", "ögrenmek");
this.verbDictionary.set("control", "kontrol");
this.verbDictionary.set("often", "siklikla");
this.verbDictionary.set("tonight", "bu gece");
this.verbDictionary.set("whose", "kimin");
this.verbDictionary.set("have", "sahip olmak");
this.verbDictionary.set("movie", "film");
this.verbDictionary.set("bed", "yatak");
this.verbDictionary.set("lose", "kaybetmek");
this.verbDictionary.set("rock", "kaya");
this.verbDictionary.set("break", "kirmak");
this.verbDictionary.set("part", "bölüm");
this.verbDictionary.set("according", "göre");
this.verbDictionary.set("strategy", "strateji");
this.verbDictionary.set("economy", "ekonomi");
this.verbDictionary.set("alone", "yalniz, tek basina");
this.verbDictionary.set("tough", "sert");
this.verbDictionary.set("prove", "kanitlamak");
this.verbDictionary.set("south", "güney");
this.verbDictionary.set("police", "polis");
this.verbDictionary.set("idea", "fikir");
this.verbDictionary.set("kid", "çocuk");
this.verbDictionary.set("evidence", "delil");
this.verbDictionary.set("recently", "son günlerde");
this.verbDictionary.set("against", "karsi");
this.verbDictionary.set("want", "istemek");
this.verbDictionary.set("like", "sevmek, begenmek");
this.verbDictionary.set("laugh", "gülmek");
this.verbDictionary.set("else", "baska");
this.verbDictionary.set("morning", "sabah");
this.verbDictionary.set("training", "egitim, antrenman");
this.verbDictionary.set("lie", "yalan");
this.verbDictionary.set("draw", "çizmek");
this.verbDictionary.set("parent", "ebeveyn");
this.verbDictionary.set("huge", "kocaman");
this.verbDictionary.set("well", "daha iyi");
this.verbDictionary.set("total", "toplam, tüm");
this.verbDictionary.set("network", "ag");
this.verbDictionary.set("list", "liste");
this.verbDictionary.set("child", "çocuk");
this.verbDictionary.set("various", "çesitli");
this.verbDictionary.set("camera", "kamera");
this.verbDictionary.set("official", "resmi");
this.verbDictionary.set("clearly", "açikça");
this.verbDictionary.set("letter", "mektup");
this.verbDictionary.set("wish", "dilek, dilemek");
this.verbDictionary.set("zoology", "hayvan bilimi");
this.verbDictionary.set("real", "reel, gerçek");
this.verbDictionary.set("wife", "kadin es");
this.verbDictionary.set("particularly", "özellikle");
this.verbDictionary.set("ready", "hazir");
this.verbDictionary.set("past", "geçmis");
this.verbDictionary.set("yourself", "kendin");
this.verbDictionary.set("then", "sonra");
this.verbDictionary.set("art", "sanat");
this.verbDictionary.set("dark", "karanlik");
this.verbDictionary.set("nearly", "neredeyse");
this.verbDictionary.set("consumer", "tüketici");
this.verbDictionary.set("cultural", "kültürel");
this.verbDictionary.set("economic", "ekonomik");
this.verbDictionary.set("fact", "gerçek");
this.verbDictionary.set("buy", "satin almak");
this.verbDictionary.set("nature", "doga");
this.verbDictionary.set("policy", "politika");
this.verbDictionary.set("body", "vücut");
this.verbDictionary.set("sort", "çesit");
this.verbDictionary.set("reflect", "yansitmak");
this.verbDictionary.set("woman", "kadin");
this.verbDictionary.set("understand", "anlamak");
this.verbDictionary.set("difference", "fark");
this.verbDictionary.set("bank", "banka");
this.verbDictionary.set("lawyer", "avukat");
this.verbDictionary.set("activity", "faaliyet, etkinlik");
this.verbDictionary.set("study", "ders çalisma");
this.verbDictionary.set("couple", "çift");
this.verbDictionary.set("act", "eylem, davranis");
this.verbDictionary.set("short", "kisa");
this.verbDictionary.set("old", "yasli, eski");
this.verbDictionary.set("appear", "görünmek, gözükmek");
this.verbDictionary.set("impact", "etki");
this.verbDictionary.set("approach", "yaklasim, yaklasma");
this.verbDictionary.set("culture", "kültür");
this.verbDictionary.set("moment", "an");
this.verbDictionary.set("send", "göndermek");
this.verbDictionary.set("property", "gayrimenkul");
this.verbDictionary.set("energy", "enerji");
this.verbDictionary.set("would", "cekmisti");
this.verbDictionary.set("detail", "ayrinti");
this.verbDictionary.set("baby", "bebek");
this.verbDictionary.set("daughter", "kiz evlat");
this.verbDictionary.set("increase", "artirmak");
this.verbDictionary.set("affect", "etkilemek, etki etmek");
this.verbDictionary.set("fund", "fon, sermaye");
this.verbDictionary.set("plant", "bitki");
this.verbDictionary.set("house", "ev");
this.verbDictionary.set("customer", "müsteri");
this.verbDictionary.set("her", "ona (kadin)");
this.verbDictionary.set("center", "merkez");
this.verbDictionary.set("kind", "tür");
this.verbDictionary.set("improve", "iyilestirmek, iyi hale getirmek");
this.verbDictionary.set("certainly", "kesinlikle");
this.verbDictionary.set("shake", "sallamak");
this.verbDictionary.set("become", "olmak, haline gelmek");
this.verbDictionary.set("herself", "kendini");
this.verbDictionary.set("four", "dört");
this.verbDictionary.set("visit", "ziyaret etmek");
this.verbDictionary.set("white", "beyaz");
this.verbDictionary.set("model", "model");
this.verbDictionary.set("during", "sirasinda");
this.verbDictionary.set("only", "bir tek");
this.verbDictionary.set("write", "yazmak");
this.verbDictionary.set("east", "dogu");
this.verbDictionary.set("remove", "kaldirmak, uzaklastirmak, ortadan kaldirmak");
this.verbDictionary.set("peace", "baris");
this.verbDictionary.set("outside", "disinda");
this.verbDictionary.set("defense", "savunma");
this.verbDictionary.set("hour", "saat");
this.verbDictionary.set("perform", "yapmak, uygulamak, yerine getirmek");
this.verbDictionary.set("account", "hesap, açiklama");
this.verbDictionary.set("mother", "anne");
this.verbDictionary.set("any", "herhangi, hiç, her");
this.verbDictionary.set("sport", "spor");
this.verbDictionary.set("wide", "genis");
this.verbDictionary.set("effort", "çaba");
this.verbDictionary.set("late", "geç");
this.verbDictionary.set("toward", "-e dogru");
this.verbDictionary.set("girl", "kiz");
this.verbDictionary.set("item", "öge");
this.verbDictionary.set("large", "genis");
this.verbDictionary.set("blood", "kan");
this.verbDictionary.set("tax", "vergi");
this.verbDictionary.set("democratic", "demokratik");
this.verbDictionary.set("himself", "kendisi");
this.verbDictionary.set("management", "yönetim");
this.verbDictionary.set("notice", "fark etmek");
this.verbDictionary.set("soon", "yakinda");
this.verbDictionary.set("fish", "balik");
this.verbDictionary.set("pass", "geçmek");
this.verbDictionary.set("material", "malzeme");
this.verbDictionary.set("project", "proje");
this.verbDictionary.set("congress", "kongre");
this.verbDictionary.set("first", "ilk");
this.verbDictionary.set("test", "test");
this.verbDictionary.set("how", "nasil");
this.verbDictionary.set("other", "diger");
this.verbDictionary.set("drug", "uyusturucu");
this.verbDictionary.set("look", "bakmak");
this.verbDictionary.set("identify", "belirlemek, tanimak, tanimlamak");
this.verbDictionary.set("little", "küçük");
this.verbDictionary.set("doctor", "doktor");
this.verbDictionary.set("financial", "mali");
this.verbDictionary.set("purpose", "amaç");
this.verbDictionary.set("while", "iken");
this.verbDictionary.set("expect", "ummak");
this.verbDictionary.set("strong", "güçlü");
this.verbDictionary.set("charge", "sarj etmek");
this.verbDictionary.set("central", "merkezi");
this.verbDictionary.set("something", "bir sey");
this.verbDictionary.set("drop", "düsürmek");
this.verbDictionary.set("space", "bosluk");
this.verbDictionary.set("board", "yazi tahtasi");
this.verbDictionary.set("five", "bes");
this.verbDictionary.set("song", "sarki");
this.verbDictionary.set("forget", "unutmak");
this.verbDictionary.set("your", "senin");
this.verbDictionary.set("walk", "yürümek");
this.verbDictionary.set("night", "gece");
this.verbDictionary.set("last", "son");
this.verbDictionary.set("quite", "oldukça");
this.verbDictionary.set("foot", "ayak");
this.verbDictionary.set("leader", "lider");
this.verbDictionary.set("about", "hakkinda, ilgili, konusunda");
this.verbDictionary.set("my", "benim");
this.verbDictionary.set("school", "okul");
this.verbDictionary.set("threat", "tehdit");
this.verbDictionary.set("claim", "iddia etmek, iddia");
this.verbDictionary.set("these", "bunlar");
this.verbDictionary.set("better", "daha iyi, daha güzel, daha iyi sekilde");
this.verbDictionary.set("gun", "silah");
this.verbDictionary.set("check", "kontrol etmek, denetlemek");
this.verbDictionary.set("open", "açik");
this.verbDictionary.set("city", "sehir");
this.verbDictionary.set("still", "hala");
this.verbDictionary.set("film", "film");
this.verbDictionary.set("food", "gida, yiyecek");
this.verbDictionary.set("benefit", "yarar, fayda");
this.verbDictionary.set("quickly", "hizli bir sekilde");
this.verbDictionary.set("and", "ve, ile");
this.verbDictionary.set("design", "tasarim");
this.verbDictionary.set("usually", "genellikle");
this.verbDictionary.set("decide", "karar vermek");
this.verbDictionary.set("page", "sayfa");
this.verbDictionary.set("stand", "ayakta durmak, direnmek");
this.verbDictionary.set("chance", "sans");
this.verbDictionary.set("long", "uzun");
this.verbDictionary.set("time", "zaman");
this.verbDictionary.set("after", "sonra, ardindan, daha sonra");
this.verbDictionary.set("local", "yerel");
this.verbDictionary.set("death", "ölüm");
this.verbDictionary.set("imagine", "hayal etmek");
this.verbDictionary.set("pretty", "güzel");
this.verbDictionary.set("actually", "aslinda, gerçekte");
this.verbDictionary.set("sing", "sarki söylemek");
this.verbDictionary.set("afterwards", "ondan sonra");
this.verbDictionary.set("now", "simdi");
this.verbDictionary.set("million", "milyon");
this.verbDictionary.set("support", "destek");
this.verbDictionary.set("cell", "hücre");
this.verbDictionary.set("this", "bu");
this.verbDictionary.set("black", "siyah");
this.verbDictionary.set("drive", "sürmek");
this.verbDictionary.set("bill", "fatura");
this.verbDictionary.set("history", "tarih");
this.verbDictionary.set("computer", "bilgisayar");
this.verbDictionary.set("technology", "teknoloji");
this.verbDictionary.set("whom", "kime");
this.verbDictionary.set("sense", "algi, duyu");
this.verbDictionary.set("recognize", "tanimak");
this.verbDictionary.set("catch", "yakalamak");
this.verbDictionary.set("month", "ay");
this.verbDictionary.set("federal", "federal");
this.verbDictionary.set("take", "almak");
this.verbDictionary.set("that", "o");
this.verbDictionary.set("hold", "tutmak");
this.verbDictionary.set("possible", "mümkün");
this.verbDictionary.set("challenge", "meydan okuma");
this.verbDictionary.set("die", "ölmek");
this.verbDictionary.set("population", "nüfus");
this.verbDictionary.set("home", "ev");
this.verbDictionary.set("ten", "on");
this.verbDictionary.set("seat", "koltuk");
this.verbDictionary.set("instead", "yerine");
this.verbDictionary.set("statement", "beyan, ifade");
this.verbDictionary.set("station", "istasyon");
this.verbDictionary.set("create", "yaratmak");
this.verbDictionary.set("beat", "dövmek, yenmek");
this.verbDictionary.set("youth", "gençlik");
this.verbDictionary.set("natural", "dogal");
this.verbDictionary.set("describe", "tanimlamak");
this.verbDictionary.set("cold", "soguk");
this.verbDictionary.set("season", "sezon");
this.verbDictionary.set("zeppelin", "zepli");
this.verbDictionary.set("evening", "aksam");
this.verbDictionary.set("low", "düsük");
this.verbDictionary.set("lay", "yatirmak");
this.verbDictionary.set("response", "cevap vermek");
this.verbDictionary.set("war", "savas");
this.verbDictionary.set("run", "kosmak");
this.verbDictionary.set("step", "adim");
this.verbDictionary.set("fill", "doldurmak");
this.verbDictionary.set("point", "puan");
this.verbDictionary.set("pattern", "desen");
this.verbDictionary.set("scene", "sahne");
this.verbDictionary.set("reality", "gerçeklik");
this.verbDictionary.set("start", "baslama");
this.verbDictionary.set("feeling", "duygu");
this.verbDictionary.set("shoulder", "omuz");
this.verbDictionary.set("happy", "mutlu");
this.verbDictionary.set("up", "yukari");
this.verbDictionary.set("eight", "sekiz");
this.verbDictionary.set("including", "dahil olmak üzere");
this.verbDictionary.set("miss", "özlemek");
this.verbDictionary.set("system", "sistem");
this.verbDictionary.set("role", "rol");
this.verbDictionary.set("finally", "en sonunda");
this.verbDictionary.set("citizen", "vatandas");
this.verbDictionary.set("already", "zaten");
this.verbDictionary.set("door", "kapi");
this.verbDictionary.set("also", "ayrica, hem de");
this.verbDictionary.set("thank", "tesekkür etmek");
this.verbDictionary.set("social", "sosyal");
this.verbDictionary.set("firm", "firma");
this.verbDictionary.set("sister", "kiz kardes");
this.verbDictionary.set("positive", "pozitif");
this.verbDictionary.set("face", "yüz");
this.verbDictionary.set("foreign", "yabanci");
this.verbDictionary.set("subject", "konu");
this.verbDictionary.set("deep", "derin");
this.verbDictionary.set("democrat", "demokrat");
this.verbDictionary.set("main", "ana");
this.verbDictionary.set("site", "alan");
this.verbDictionary.set("reveal", "ortaya çikartmak, açiga vurmak");
this.verbDictionary.set("free", "ücretsiz");
this.verbDictionary.set("agreement", "anlasma, sözlesme");
this.verbDictionary.set("agent", "ajan");
this.verbDictionary.set("century", "yüzyil");
this.verbDictionary.set("anyone", "kimse, herhangi biri, hiç kimse");
this.verbDictionary.set("hope", "umut");
this.verbDictionary.set("individual", "bireysel");
this.verbDictionary.set("resource", "kaynak");
this.verbDictionary.set("include", "dahil etmek");
this.verbDictionary.set("billion", "milyar");
this.verbDictionary.set("cause", "sebep olmak");
this.verbDictionary.set("same", "ayni");
this.verbDictionary.set("week", "hafta");
this.verbDictionary.set("thousand", "bin");
this.verbDictionary.set("question", "soru");
this.verbDictionary.set("man", "adam, insan");
this.verbDictionary.set("water", "su");
this.verbDictionary.set("available", "müsait");
this.verbDictionary.set("field", "tarla, alan");
this.verbDictionary.set("small", "küçük");
this.verbDictionary.set("record", "kayit");
this.verbDictionary.set("force", "kuvvet");
this.verbDictionary.set("weapon", "silah");
this.verbDictionary.set("product", "ürün");
this.verbDictionary.set("trade", "ticaret");
this.verbDictionary.set("before", "önce");
this.verbDictionary.set("to", "mastar (mek, mak), karsi");
this.verbDictionary.set("television", "televizyon");
this.verbDictionary.set("they", "onlar");
this.verbDictionary.set("order", "siparis, siparis vermek");
this.verbDictionary.set("Mr", "bay");
this.verbDictionary.set("weight", "agirlik");
this.verbDictionary.set("amount", "miktar, tutar");
this.verbDictionary.set("carry", "tasimak");
this.verbDictionary.set("special", "özel");
this.verbDictionary.set("anywhere", "herhangi bir yere");
this.verbDictionary.set("every", "her");
this.verbDictionary.set("know", "bilmek");
this.verbDictionary.set("more", "daha");
this.verbDictionary.set("admit", "kabul etmek, itiraf etmek");
this.verbDictionary.set("picture", "resim");
this.verbDictionary.set("love", "ask");
this.verbDictionary.set("need", "ihtiyaç, gereksinim");
this.verbDictionary.set("security", "güvenlik");
this.verbDictionary.set("ago", "önce, evvel");
this.verbDictionary.set("near", "yakin");
this.verbDictionary.set("year", "yil");
this.verbDictionary.set("zebra", "zebra");
this.verbDictionary.set("race", "yaris");
this.verbDictionary.set("knowledge", "bilgi");
this.verbDictionary.set("since", "dan beri");
this.verbDictionary.set("popular", "popüler");
this.verbDictionary.set("report", "rapor");
this.verbDictionary.set("fail", "basarisiz");
this.verbDictionary.set("his", "onun (erkek)");
this.verbDictionary.set("production", "üretim");
this.verbDictionary.set("agree", "katilmak, hem fikir olmak");
this.verbDictionary.set("analysis", "analiz, çözümleme");
this.verbDictionary.set("fine", "iyi, güzel");
this.verbDictionary.set("everything", "her sey");
this.verbDictionary.set("remain", "kalmak, sürdürmek");
this.verbDictionary.set("science", "bilim");
this.verbDictionary.set("future", "gelecek");
this.verbDictionary.set("pain", "agri");
this.verbDictionary.set("election", "seçim");
this.verbDictionary.set("north", "kuzey");
this.verbDictionary.set("together", "birlikte");
this.verbDictionary.set("sure", "emin");
this.verbDictionary.set("involve", "içermek, kapsamak");
this.verbDictionary.set("happen", "olmak");
this.verbDictionary.set("officer", "memur");
this.verbDictionary.set("land", "arazi, toprak");
this.verbDictionary.set("live", "canli");
this.verbDictionary.set("so", "yani");
this.verbDictionary.set("though", "olsa da");
this.verbDictionary.set("media", "medya");
this.verbDictionary.set("practice", "uygulama, pratik");
this.verbDictionary.set("generation", "nesil");
this.verbDictionary.set("important", "önemli");
this.verbDictionary.set("may", "mayis ayi");
this.verbDictionary.set("pay", "ödemek");
this.verbDictionary.set("continue", "devam etmek");
this.verbDictionary.set("what", "ne");
this.verbDictionary.set("realize", "fark etmek");
this.verbDictionary.set("move", "hareket etmek");
this.verbDictionary.set("community", "topluluk");
this.verbDictionary.set("ball", "top");
this.verbDictionary.set("edge", "kenar, kiyi");
this.verbDictionary.set("add", "eklemek, ilave etmek");
this.verbDictionary.set("show", "göstermek");
this.verbDictionary.set("theory", "teori");
this.verbDictionary.set("okay", "tamam");
this.verbDictionary.set("just", "sadece");
this.verbDictionary.set("which", "hangi");
this.verbDictionary.set("try", "denemek");
this.verbDictionary.set("safe", "güvenli");
this.verbDictionary.set("job", "meslek");
this.verbDictionary.set("matter", "konu, mesele");
this.verbDictionary.set("market", "pazar");
this.verbDictionary.set("build", "insa etmek");
this.verbDictionary.set("a", "bir");
this.verbDictionary.set("wait", "beklemek");
this.verbDictionary.set("debate", "müzakere, tartisma");
this.verbDictionary.set("remember", "hatirlamak");
this.verbDictionary.set("member", "üye");
this.verbDictionary.set("thus", "böylece");
this.verbDictionary.set("coach", "koç");
this.verbDictionary.set("truth", "hakikat");
this.verbDictionary.set("direction", "yön");
this.verbDictionary.set("maintain", "sürdürmek");
this.verbDictionary.set("air", "hava");
this.verbDictionary.set("tell", "söylemek");
this.verbDictionary.set("who", "kim");
this.verbDictionary.set("nice", "iyi, güzel");
this.verbDictionary.set("size", "boyut");
this.verbDictionary.set("course", "ders");
this.verbDictionary.set("yet", "henüz");
this.verbDictionary.set("magazine", "dergi");
this.verbDictionary.set("compare", "karsilastirmak");
this.verbDictionary.set("raise", "yükseltmek");
this.verbDictionary.set("come", "gelmek");
this.verbDictionary.set("present", "mevcut");
this.verbDictionary.set("fall", "düsmek");
this.verbDictionary.set("seek", "aramak");
this.verbDictionary.set("republican", "cumhuriyetçi");
this.verbDictionary.set("return", "dönüs");
this.verbDictionary.set("afternoon", "ögleden sonra");
this.verbDictionary.set("building", "bina");
this.verbDictionary.set("yes", "evet");
this.verbDictionary.set("day", "gün");
this.verbDictionary.set("prevent", "engel olmak");
this.verbDictionary.set("eat", "yemek yemek");
this.verbDictionary.set("class", "sinif");
this.verbDictionary.set("seven", "yedi");
this.verbDictionary.set("use", "kullanmak");
this.verbDictionary.set("pull", "çekmek");
this.verbDictionary.set("specific", "özel");
this.verbDictionary.set("choice", "seçim, seçenek");
this.verbDictionary.set("office", "ofis");
this.verbDictionary.set("enough", "yeterli");
this.verbDictionary.set("growth", "büyüme");
this.verbDictionary.set("writer", "yazar");
this.verbDictionary.set("nothing", "hiçbir sey");
this.verbDictionary.set("say", "söylemek");
this.verbDictionary.set("street", "sokak");
this.verbDictionary.set("enter", "girmek, katilmak");
this.verbDictionary.set("window", "pencere");
this.verbDictionary.set("image", "görüntü, resim");
this.verbDictionary.set("there", "orada");
this.verbDictionary.set("teacher", "ögretmen");
this.verbDictionary.set("organization", "organizasyon");
this.verbDictionary.set("leg", "bacak");
this.verbDictionary.set("red", "kirmizi");
this.verbDictionary.set("less", "az");
this.verbDictionary.set("never", "asla");
this.verbDictionary.set("budget", "bütçe");
this.verbDictionary.set("western", "batida");
this.verbDictionary.set("hundred", "yüz");
this.verbDictionary.set("leave", "ayrilmak");
this.verbDictionary.set("their", "onlarin");
this.verbDictionary.set("position", "pozisyon");
this.verbDictionary.set("six", "alti");
this.verbDictionary.set("suffer", "aci çekmek");
this.verbDictionary.set("hotel", "otel");
this.verbDictionary.set("avoid", "önlemek, kaçinmak");
this.verbDictionary.set("behind", "arkasinda, gerisinde");
this.verbDictionary.set("nor", "ne de");
this.verbDictionary.set("skin", "cilt");
this.verbDictionary.set("meet", "bulusmak");
this.verbDictionary.set("line", "çizgi, sira");
this.verbDictionary.set("level", "seviye");
this.verbDictionary.set("simple", "basit");
this.verbDictionary.set("color", "renk");
this.verbDictionary.set("own", "kendi");
this.verbDictionary.set("someone", "birisi");
this.verbDictionary.set("mission", "misyon");
this.verbDictionary.set("base", "üs, temel, baz");
this.verbDictionary.set("full", "tam");
this.verbDictionary.set("high", "yüksek");
this.verbDictionary.set("international", "uluslararasi");
this.verbDictionary.set("allow", "izin vermek");
this.verbDictionary.set("perhaps", "belki");
this.verbDictionary.set("change", "degisiklik");
this.verbDictionary.set("ahead", "önde, ileri");
this.verbDictionary.set("kitchen", "mutfak");
this.verbDictionary.set("tend", "yönelmek, egilmek");
this.verbDictionary.set("state", "devlet, durum");
this.verbDictionary.set("measure", "ölçmek");
this.verbDictionary.set("vote", "oy");
this.verbDictionary.set("set", "ayarlamak");
this.verbDictionary.set("should", "meli, mali");
this.verbDictionary.set("form", "form");
this.verbDictionary.set("bar", "bar");
this.verbDictionary.set("glass", "bardak");
this.verbDictionary.set("throughout", "boyunca");
this.verbDictionary.set("choose", "seçmek");
this.verbDictionary.set("along", "boyunca, yani sira");
this.verbDictionary.set("worker", "isçi");
this.verbDictionary.set("public", "halka açik");
this.verbDictionary.set("despite", "ragmen, aksine");
this.verbDictionary.set("place", "yer, mekan");
this.verbDictionary.set("friend", "arkadas");
this.verbDictionary.set("case", "dava");
this.verbDictionary.set("april", "nisan");
this.verbDictionary.set("language", "dil");
this.verbDictionary.set("behavior", "davranis, tutum, hareket");
this.verbDictionary.set("several", "birkaç");
this.verbDictionary.set("later", "sonra");
this.verbDictionary.set("national", "ulusal");
this.verbDictionary.set("opportunity", "firsat");
this.verbDictionary.set("successful", "basarili");
this.verbDictionary.set("artist", "sanatçi");
this.verbDictionary.set("candidate", "aday");
this.verbDictionary.set("best", "en iyi, en iyisi, en");
this.verbDictionary.set("keep", "tutmak");
this.verbDictionary.set("lot", "çok");
this.verbDictionary.set("event", "olay");
this.verbDictionary.set("let", "izin vermek");
this.verbDictionary.set("out", "disari");
this.verbDictionary.set("whatever", "her neyse");
this.verbDictionary.set("fear", "korku");
this.verbDictionary.set("area", "alan, bölge");
this.verbDictionary.set("story", "öykü");
this.verbDictionary.set("left", "ayrildi");
this.verbDictionary.set("problem", "problem, sorun");
this.verbDictionary.set("middle", "orta");
this.verbDictionary.set("feel", "hissetmek");
this.verbDictionary.set("focus", "odaklanmak");
this.verbDictionary.set("dog", "köpek");
this.verbDictionary.set("newspaper", "gazete");
this.verbDictionary.set("employee", "çalisan");
this.verbDictionary.set("hospital", "hastane");
this.verbDictionary.set("surface", "yüzey");
this.verbDictionary.set("power", "güç");
this.verbDictionary.set("industry", "endüstri");
this.verbDictionary.set("fly", "uçmak");
this.verbDictionary.set("zoom", "yakinlasmak, zoom yapmak");
this.verbDictionary.set("method", "yöntem");
this.verbDictionary.set("hair", "saç");
this.verbDictionary.set("Mrs", "bayan");
this.verbDictionary.set("shot", "atis");
this.verbDictionary.set("finger", "parmak");
this.verbDictionary.set("action", "eylem, etki, hareket");
this.verbDictionary.set("sit", "oturmak");
this.verbDictionary.set("stop", "dur, durmak");
this.verbDictionary.set("receive", "teslim almak");
this.verbDictionary.set("painting", "boyama");
this.verbDictionary.set("education", "egitim");
this.verbDictionary.set("everyone", "herkes, her biri");
this.verbDictionary.set("beautiful", "güzel");
this.verbDictionary.set("gas", "gaz");
this.verbDictionary.set("similar", "benzer");
this.verbDictionary.set("trial", "deneme, test");
this.verbDictionary.set("recent", "son");
this.verbDictionary.set("father", "baba");
this.verbDictionary.set("box", "kutu");
this.verbDictionary.set("those", "bunlar");
this.verbDictionary.set("note", "not");
this.verbDictionary.set("find", "bulmak");
this.verbDictionary.set("military", "askeri");
this.verbDictionary.set("win", "kazanmak");
this.verbDictionary.set("concern", "iliskisi olmak, ait olmak, ilgilendirmek");
this.verbDictionary.set("factor", "faktör");
this.verbDictionary.set("grow", "büyümek");
this.verbDictionary.set("team", "takim");
this.verbDictionary.set("bad", "kötü");
this.verbDictionary.set("hand", "el");
this.verbDictionary.set("structure", "yapi");
this.verbDictionary.set("range", "menzil, aralik");
this.verbDictionary.set("campaign", "kampanya");
this.verbDictionary.set("serve", "servis");
this.verbDictionary.set("finish", "bitis");
this.verbDictionary.set("garden", "bahçe");
this.verbDictionary.set("private", "özel");
this.verbDictionary.set("not", "degil");
this.verbDictionary.set("cost", "maliyet");
this.verbDictionary.set("section", "bölüm, kesit");
this.verbDictionary.set("violence", "siddet");
this.verbDictionary.set("onto", "üstüne");
this.verbDictionary.set("she", "o (kadin)");
this.verbDictionary.set("many", "çok");
this.verbDictionary.set("guess", "tahmin");
this.verbDictionary.set("believe", "inanmak");
this.verbDictionary.set("dinner", "aksam yemegi");
this.verbDictionary.set("turn", "çevirmek");
this.verbDictionary.set("entire", "tamami");
this.verbDictionary.set("all right", "peki");
this.verbDictionary.set("somebody", "birileri");
this.verbDictionary.set("car", "araba");
this.verbDictionary.set("we", "biz");
this.verbDictionary.set("player", "oyuncu");
this.verbDictionary.set("suggest", "önermek");
this.verbDictionary.set("president", "devlet baskani");
this.verbDictionary.set("pressure", "basinç");
this.verbDictionary.set("back", "geri");
this.verbDictionary.set("yard", "avlu");
this.verbDictionary.set("side", "yan");
this.verbDictionary.set("way", "yol, yön, yöntem");
this.verbDictionary.set("hit", "çarpmak");
this.verbDictionary.set("without", "olmadan");
this.verbDictionary.set("key", "anahtar");
this.verbDictionary.set("responsibility", "sorumluluk");
this.verbDictionary.set("throw", "atmak");
this.verbDictionary.set("represent", "temsil etmek");
this.verbDictionary.set("rather", "daha dogrusu");
this.verbDictionary.set("share", "paylasmak");
this.verbDictionary.set("executive", "yönetici");
this.verbDictionary.set("themselves", "kendilerini");
this.verbDictionary.set("reason", "neden");
this.verbDictionary.set("tree", "agaç");
this.verbDictionary.set("mouth", "agiz");
this.verbDictionary.set("you", "sen");



    
   }


}
